// Seeded, escape-first cooperative policy. Uses only public engine actions; no hidden deck peeking.
const fs=require('node:fs'),path=require('node:path');require('../terrain-data.js');const E=require('../engine.js');
const solution=[{"shape":"S","rotation":0,"flip":false,"x":6,"y":1},{"shape":"L","rotation":3,"flip":true,"x":4,"y":3},{"shape":"S","rotation":0,"flip":true,"x":5,"y":8},{"shape":"S","rotation":1,"flip":true,"x":7,"y":6},{"shape":"I","rotation":0,"flip":false,"x":4,"y":6},{"shape":"S","rotation":0,"flip":true,"x":7,"y":3},{"shape":"S","rotation":0,"flip":true,"x":9,"y":3},{"shape":"T","rotation":2,"flip":false,"x":11,"y":4},{"shape":"S","rotation":0,"flip":true,"x":9,"y":5},{"shape":"S","rotation":0,"flip":false,"x":0,"y":4},{"shape":"T","rotation":2,"flip":false,"x":1,"y":5},{"shape":"O","rotation":0,"flip":false,"x":3,"y":4}];
const componentSpots={engine:[[5,0]],cooler:[[5,7]],battery:[[5,4],[7,4]]};
function simulate(seed){const g=E.newGame({players:4,seed},global.DINO_TERRAIN),metrics={seed,turns:0,actions:{},cards:0,gathered:{},crafted:{},dinosaurSpawns:0,collapsed:0,rescues:0,hunts:0,noUsefulCardEnds:0,cyclingTrips:0,snapshots:[],trace:[]};let loop=0,lastTurn='';const returning=new Set,targets=new Map;
const p=()=>E.active(g),occupied=()=>E.aircraftCells().filter(c=>g.aircraft.zones[c.zone].cells[c.index]).length;
const act=(type,a={})=>{const before={round:g.round,turn:g.turn,actions:g.actions,hand:p().hand.length,cardCost:type==='commitPayment'?(g.payment?.cards.length||0):['move','explore','hide','rest','survey'].includes(type)?1:type==='gatherTake'&&!g.gathering?.paid?1:0,discard:g.terrainDiscard.length,dino:!!g.dino,rescues:g.players.reduce((n,p)=>n+p.rescueCount,0)};E.act(g,type,a);const same=before.turn===g.turn&&before.round===g.round,spent=same?before.actions-g.actions:(type==='move'||type==='battlePlan'?1:0);if(spent>0)metrics.actions[type]=(metrics.actions[type]||0)+spent;metrics.cards+=before.cardCost;if(!before.dino&&g.dino)metrics.dinosaurSpawns++;metrics.rescues+=g.players.reduce((n,p)=>n+p.rescueCount,0)-before.rescues;metrics.collapsed+=Math.max(0,g.terrainDiscard.length-before.discard);if(type==='battlePlan')metrics.hunts++;if(['move','explore','startGather','hide','survey','end','beginPayment','installAircraft'].includes(type))metrics.trace.push({r:before.round,p:before.turn,type,...a});};
const normalCard=()=>p().hand.findIndex(c=>E.CARDS[c]&&c!=='hunger');
const disposable=()=>{const rank=c=>c.startsWith('quest:')?0:c==='explore'?2:c==='run'?3:c==='gather'?4:c==='harvest'?5:c==='hide'?6:1;return p().hand.map((c,i)=>({i,s:rank(c)})).sort((a,b)=>a.s-b.s)[0]?.i??-1;};
const availableItems=()=>p().bag.concat(g.campSupplies.warehouse);
const cellFilled=(x,y)=>{const c=E.aircraftCells().find(c=>c.x===x&&c.y===y);return !!g.aircraft.zones[c.zone].cells[c.index];};
const remaining=kind=>kind==='steel'?48-E.aircraftCells().filter(c=>c.kind==='steel'&&cellFilled(c.x,c.y)).length:componentSpots[kind].filter(([x,y])=>!cellFilled(x,y)).length;
function teamNeeds(){const left={steel:Math.ceil(remaining('steel')/4),engine:remaining('engine'),cooler:remaining('cooler'),battery:remaining('battery')};const items=g.players.flatMap(p=>p.bag).concat(g.campSupplies.warehouse,g.loot);for(const i of items)if(left[i.kind]!==undefined)left[i.kind]=Math.max(0,left[i.kind]-(i.kind==='steel'?E.itemCells(i).length/4:1));const need={metal:left.steel+2*left.engine+left.cooler,branch:left.steel,stone:left.engine,stem:left.engine+left.cooler,water:left.cooler};for(const i of items)if(need[i.kind]!==undefined)need[i.kind]--;return {need,left};}
function value(item){const {need,left}=teamNeeds(),k=item.kind;if(componentSpots[k])return left[k]>0?30:2;if(k==='steel')return remaining('steel')>0?20:1;if(k==='metal')return need.metal>0?12:1;if(k==='stone')return need.stone>0||need.metal>0?8:1;if(k==='branch')return need.branch>0?7:1;if(k==='stem')return need.stem>0?8:1;if(k==='water'&&need.water>0)return 8;if(E.foodValue(item)>0){const food=p().bag.reduce((s,i)=>s+E.foodValue(i),0);return food<2?5:food<4?2:0;}return k==='knife'?3:0;}
function fit(item,owner=p()){for(let rotation=0;rotation<4;rotation++)for(const c of E.bagCells(owner))if(E.bagFits(owner,{...item,rotation},c.x,c.y))return {x:c.x,y:c.y,rotation};return null;}
function pay(type,data){act('beginPayment',{type,data});for(const [k,n]of Object.entries(g.payment.cost))for(const item of p().bag.filter(i=>i.kind===k&&!i.topping).slice(0,n))act('offerPayment',{id:item.id});act('commitPayment');metrics.crafted[type+':'+(data.recipe||'food')]=(metrics.crafted[type+':'+(data.recipe||'food')]||0)+1;}
function install(){for(const item of p().bag){if(item.kind==='steel'){for(const s of solution)if(item.steelShape===s.shape&&E.canInstallAircraft(g,{id:item.id,zone:'grid',...s})){act('installAircraft',{id:item.id,zone:'grid',...s});return true;}}else if(componentSpots[item.kind])for(const [x,y]of componentSpots[item.kind])if(E.canInstallAircraft(g,{id:item.id,zone:'grid',x,y})){act('installAircraft',{id:item.id,zone:'grid',x,y});return true;}}return false;}
function campWork(){returning.delete(p().id);if(install())return true;for(const i of p().bag)if(componentSpots[i.kind]&&!remaining(i.kind)){act('discardItem',{id:i.id});return true;}for(const item of p().bag){if(['battery','engine','cooler','steel'].includes(item.kind))continue;if(['stem','herb','knife'].includes(item.kind)&&!teamNeeds().need[item.kind]){act('discardItem',{id:item.id});return true;}const store=E.campStore(g,'warehouse');let can=false;for(let y=0;y<store.h;y++)for(let x=0;x<store.w;x++)if(E.campFits(store,item,x,y))can=true;if(can){act('campPut',{id:item.id,area:'warehouse'});return true;}}
 // Complete one recipe atomically through normal payment before putting materials away again.
 const all=availableItems(),has=cost=>Object.entries(cost).every(([k,n])=>all.filter(i=>i.kind===k&&!i.topping).length>=n),idx=normalCard();if(idx<0)return false;let recipe,type,steelShape;for(const kind of ['engine','cooler','steel']){if(!remaining(kind)||!has(E.AIRCRAFT_RECIPES[kind].cost))continue;recipe=kind;type='aircraftCraft';if(kind==='steel'){const target=solution.find(s=>E.itemCells({kind:'steel',steelShape:s.shape,rotation:s.rotation,flip:s.flip}).every(([x,y])=>!cellFilled(x+s.x,y+s.y)));if(!target)continue;steelShape=target.shape;}break;}
 if(!recipe&&teamNeeds().need.metal>0&&has({stone:2})){type='campCraft';recipe='metal';}if(!recipe)return false;
 const cost=(type==='campCraft'?E.CAMP_RECIPES:E.AIRCRAFT_RECIPES)[recipe].cost;for(const [kind,n]of Object.entries(cost)){while(E.count(p(),kind)<n){const item=g.campSupplies.warehouse.find(i=>i.kind===kind&&!i.topping);if(!item||!fit(item))return false;act('campTake',{id:item.id,area:'warehouse'});}}
 pay(type,{recipe,card:idx,...(steelShape?{steelShape}:{})});return true;
}
function go(to){const route=E.routes(g,p().pos,80)[to];if(!route?.length||!p().hand.length)return false;const run=p().hand.indexOf('run'),step=run>=0&&route.length>1?route[1]:route[0];if(!E.capacityOK(g,step))return false;act('move',{card:run>=0&&route.length>1?run:disposable(),to:step,...(run>=0&&route.length>1?{run:true}:{})});return true;}
function resourcesAt(key){const t=g.tiles[key];return t.resources.map((kind,index)=>({kind,index})).concat(E.groundItems(g,key).map(i=>({...i,groundId:i.id})));}
while(!g.ended&&loop++<12000){const stamp=g.round+':'+g.turn;if(stamp!==lastTurn){lastTurn=stamp;metrics.turns++;targets.delete(p().id);if(g.turn===0)metrics.snapshots.push({round:g.round,filled:occupied(),shared:g.sharedDetection,rescues:metrics.rescues});}
 if(g.huntResult){act('confirmHuntResult');continue;}
 if(g.pendingEvent){act(g.pendingEvent.stage==='draw'?'drawEvent':'resolveEvent');continue;}
 if(g.battle){const b=g.battle;if(b.stage==='plan'){const options=E.combatOptions(p()).sort((a,b)=>(E.combatCardData(b.card).atk||0)-(E.combatCardData(a.card).atk||0));act('battlePlan',{cards:options.slice(0,3).map(o=>o.selection)});}else if(b.stage==='resolve')act('battleStep');else if(b.hp<=3&&g.actions>0&&p().hp>=4)act('battleContinue');else act('battleStop');continue;}
 if(g.tileSetup){act('autoSupplyTile');continue;}
 if(g.pendingExplore){const key=g.pendingExplore.to,t=g.tiles[key],want=E.capacityOK(g,key)&&!t.safe&&(resourcesAt(key).some(i=>value(i)>=5)||teamNeeds().left.battery>0&&t.level===2)&&(!t.hunt||g.actions>0&&p().hp>=5);act('resolveExplore',{move:want});continue;}
 if(g.loot.length){const before=g.loot.length;act('autoCollectLoot');if(g.loot.length===before){if(p().pos==='0,0'&&p().bag.length){const item=p().bag[0];try{act('campPut',{id:item.id,area:'warehouse'});continue;}catch{}}act('discardLoot',{id:g.loot[0].id});}continue;}
 if(g.gathering){const choices=resourcesAt(p().pos).filter(i=>fit(i)).sort((a,b)=>value(b)-value(a));if(choices.length&&(value(choices[0])>0||g.gathering.all&&!E.canFinishGather(g))){const item=choices[0];metrics.gathered[item.kind]=(metrics.gathered[item.kind]||0)+1;act('gatherTake',{...(item.groundId?{groundId:item.groundId}:{index:item.index}),...fit(item)});}else act('finishGather');continue;}
 const food=p().bag.filter(i=>E.canEat(p(),i)&&!(i.kind==='meat'&&p().hp<=2)).sort((a,b)=>E.foodValue(b)-E.foodValue(a));if(p().hunger<=3&&food.length){act('eat',{id:food[0].id});continue;}
 if(p().pos==='0,0'&&campWork())continue;
 if(E.aircraftProgress(g).ready){if(g.players.every(p=>p.pos==='0,0')){act('departAircraft');break;}if(p().pos!=='0,0'&&g.actions&&go('0,0'))continue;act('end');continue;}
 if(!g.actions||!p().hand.length){act('end');continue;}
 const t=g.tiles[p().pos],home=E.routes(g,p().pos,80)['0,0'],load=p().bag.reduce((n,i)=>n+E.itemCells(i).length,0);
 if(p().pos!=='0,0'&&(returning.has(p().id)||load>=8||p().hunger<=(home?.length||2)+1||p().hp<=3||p().bag.some(i=>i.kind==='battery')||g.dino&&p().detection>=6)){returning.add(p().id);if(go('0,0'))continue;}
 const hide=p().hand.indexOf('hide');if(hide>=0&&g.sharedDetection>=5&&p().pos!=='0,0'){act('hide',{card:hide});continue;}
 if(teamNeeds().left.battery>0&&t.level===2&&!t.hunt&&!p().surveyed){act('survey',{card:disposable()});continue;}
 const gather=p().hand.findIndex(c=>c==='gather'||c==='harvest');if(gather>=0&&resourcesAt(p().pos).some(i=>value(i)>=3&&fit(i))){act('startGather',{card:gather});continue;}
 const routes=E.routes(g,p().pos,80);const ranked=Object.keys(routes).filter(k=>k!==p().pos&&k!=='0,0'&&E.capacityOK(g,k)&&!(g.tiles[k].hunt&&p().hp<5)).map(k=>({k,score:((g.tiles[k].level===2&&!g.tiles[k].hunt&&!p().surveyed&&teamNeeds().left.battery>0)?18:0)+(gather>=0?resourcesAt(k).filter(i=>fit(i)).sort((a,b)=>value(b)-value(a)).slice(0,3).reduce((n,i)=>n+value(i),0):0)-routes[k].length*5-(g.tiles[k].hunt?6:0)})).filter(v=>v.score>2).sort((a,b)=>b.score-a.score);
 if(ranked.length&&go(ranked[0].k))continue;
 const explore=p().hand.indexOf('explore');if(explore>=0&&(g.terrainDeck.length||g.terrainDiscard.length)){const empty=E.exploreTargets(g).sort((a,b)=>E.dist(a,'0,0')-E.dist(b,'0,0')||a.localeCompare(b));if(empty.length){const to=empty[0],level=teamNeeds().left.battery>0&&!p().surveyed&&E.dist(to,'0,0')>=2?2:1;act('explore',{card:explore,to,level});continue;}}
 if(p().pos!=='0,0'&&p().bag.length&&go('0,0'))continue;
 if(explore>=0){const frontier=Object.keys(routes).filter(k=>E.neighbors(k).some(n=>!g.tiles[n])&&E.capacityOK(g,k)).sort((a,b)=>routes[a].length-routes[b].length);if(frontier[0]&&go(frontier[0]))continue;}
 if(p().pos==='0,0'&&!p().hand.includes('explore')){const near=E.neighbors('0,0').find(k=>g.tiles[k]&&E.capacityOK(g,k)&&!g.tiles[k].hunt&&!g.tiles[k].event);if(near){metrics.cyclingTrips++;returning.add(p().id);if(go(near))continue;}}metrics.noUsefulCardEnds++;act('end');
}
if(loop>=12000)throw new Error('Policy loop '+seed+' '+JSON.stringify({round:g.round,turn:g.turn,pos:p().pos,hand:p().hand,loot:g.loot,bag:p().bag,warehouse:g.campSupplies.warehouse}));
return {...metrics,won:!!g.aircraft.departed,rounds:g.aircraft.departed?g.round:30,filled:occupied(),missing:E.aircraftCells().filter(c=>!cellFilled(c.x,c.y)).reduce((a,c)=>(a[c.kind]=(a[c.kind]||0)+1,a),{}),remainingRaw:teamNeeds().need,warehouse:g.campSupplies.warehouse.map(i=>i.kind),finalPlayers:g.players.map(p=>({pos:p.pos,rescues:p.rescueCount,bag:p.bag.map(i=>i.kind)}))};}
if(require.main===module){const seeds=process.argv.includes('--pilot')?[24001]:Array.from({length:10},(_,i)=>24001+i*7919);const runs=[];for(const seed of seeds){const r=simulate(seed);runs.push(r);console.log(JSON.stringify({seed,won:r.won,rounds:r.rounds,turns:r.turns,filled:r.filled,missing:r.missing,actions:r.actions,rescues:r.rescues}));}const out=path.resolve(process.env.DINO_BALANCE_OUTPUT||path.join(__dirname,process.argv.includes('--pilot')?'pilot.json':'runs-v024.json'));fs.writeFileSync(out,JSON.stringify({version:'0.24',players:4,sourceSHA256:Object.fromEntries(['../engine.js','../terrain-data.js','simulate.cjs'].map(file=>[file,require('node:crypto').createHash('sha256').update(fs.readFileSync(path.resolve(__dirname,file))).digest('hex')])),policy:'escape-first cooperative; visible-state greedy; pre-solved aircraft tiling; no building upgrades',runs},null,2)+'\n');}
module.exports={simulate};
