/* Pointer-based construction drag: the grabbed cell remains under the pointer. */
(() => {
 function install(root,ctx){let drag=null,suppressUntil=0;
  const clear=()=>root.querySelectorAll('.grid-cell.valid-preview,.grid-cell.invalid-preview').forEach(n=>n.classList.remove('valid-preview','invalid-preview'));
  function cancel(){if(!drag)return;drag.ghost?.remove();drag.source?.classList.remove('construction-dragging');if(root.hasPointerCapture(drag.pointer))root.releasePointerCapture(drag.pointer);drag=null;clear();}
  function hit(x,y){const grid=document.elementFromPoint(x,y)?.closest('[data-board]');if(!grid)return null;const board=ctx.board(grid.dataset.board),cell=grid.querySelector('[data-cell]');if(!board||!cell)return null;const r=grid.getBoundingClientRect(),cr=cell.getBoundingClientRect(),style=getComputedStyle(grid),gx=parseFloat(style.columnGap)||0,gy=parseFloat(style.rowGap)||0,pitchX=cr.width+gx,pitchY=cr.height+gy,cells=ctx.cells(),anchor=cells[drag.anchor]||cells[0],col=Math.floor((x-r.left)/pitchX),row=Math.floor((y-r.top)/pitchY);return {board:board.id,x:col-anchor[0],y:row-anchor[1],left:r.left,top:r.top,pitchX,pitchY,gx,gy,width:cr.width,height:cr.height};}
  function paint(x,y){if(!drag?.moving)return;drag.x=x;drag.y=y;const cells=ctx.cells(),anchor=cells[drag.anchor]||cells[0],target=hit(x,y),w=Math.max(...cells.map(c=>c[0]))+1,h=Math.max(...cells.map(c=>c[1]))+1,unit=target?.pitchX||32,vertical=target?.pitchY||32,gx=target?.gx||2,gy=target?.gy||2;drag.target=target;clear();if(target)ctx.preview(`${target.board}:${target.x}:${target.y}`);const left=target?target.left+target.x*unit:x-(anchor[0]+.5)*unit,top=target?target.top+target.y*vertical:y-(anchor[1]+.5)*vertical,ok=target&&ctx.canPlace(target);drag.ghost.dataset.anchor=anchor.join(',');drag.ghost.dataset.origin=target?`${target.board}:${target.x}:${target.y}`:'';drag.ghost.style.cssText=`position:fixed;left:${left}px;top:${top}px;width:${w*unit-gx}px;height:${h*vertical-gy}px;pointer-events:none;z-index:1500;`;drag.ghost.innerHTML=cells.map(([a,b])=>`<i style="position:absolute;left:${a*unit}px;top:${b*vertical}px;width:${unit-gx}px;height:${vertical-gy}px;background:${ctx.color()};border:2px solid ${target?(ok?'#426c4b':'#b86146'):'#6e805a'};border-radius:4px;opacity:${target ? .72 : .9};box-sizing:border-box"></i>`).join('');}
  root.addEventListener('pointerdown',e=>{if(e.button!==0||!ctx.enabled())return;const preview=e.target.closest('[data-piece]'),cell=e.target.closest('[data-cell]');let piece,anchor=0;if(preview){piece=ctx.current();if(!piece)return;const rect=e.target.closest('[data-piece-x]');if(rect)anchor=ctx.cells().findIndex(([x,y])=>x===+rect.dataset.pieceX&&y===+rect.dataset.pieceY);}else if(cell){const [id,x,y]=cell.dataset.cell.split(':'),b=ctx.board(id),c=b?.cells[+y*b.w+(+x)];if(!c||!ctx.isStorage(id))return;ctx.select(c);piece=ctx.current();anchor=ctx.cells().findIndex(([a,b])=>a+c.x===+x&&b+c.y===+y);}else return;e.preventDefault();e.stopImmediatePropagation();drag={pointer:e.pointerId,source:preview||cell,startX:e.clientX,startY:e.clientY,x:e.clientX,y:e.clientY,anchor:Math.max(0,anchor),moving:false};root.setPointerCapture(e.pointerId);},true);
  root.addEventListener('pointermove',e=>{if(!drag)return;e.preventDefault();e.stopImmediatePropagation();if(!drag.moving&&Math.hypot(e.clientX-drag.startX,e.clientY-drag.startY)<5)return;if(!drag.moving){drag.moving=true;drag.ghost=document.createElement('div');drag.ghost.className='construction-drag-ghost';drag.ghost.setAttribute('aria-hidden','true');document.body.append(drag.ghost);drag.source.classList.add('construction-dragging');}paint(e.clientX,e.clientY);const area=document.elementFromPoint(e.clientX,e.clientY)?.closest('.boards');if(area){const r=area.getBoundingClientRect();if(e.clientY>r.bottom-25)area.scrollTop+=9;else if(e.clientY<r.top+25)area.scrollTop-=9;}},true);
  root.addEventListener('pointerup',e=>{if(!drag)return;e.preventDefault();e.stopImmediatePropagation();const d=drag,target=d.moving?hit(e.clientX,e.clientY):null,rect=d.source.getBoundingClientRect();suppressUntil=Date.now()+400;cancel();if(target)ctx.place(target,{rect,dragged:true,dropPoint:{x:e.clientX,y:e.clientY}});else ctx.render();},true);
  root.addEventListener('click',e=>{if(Date.now()<suppressUntil){e.preventDefault();e.stopImmediatePropagation();}},true);
  root.addEventListener('pointercancel',cancel,true);window.addEventListener('blur',cancel);
  document.addEventListener('keydown',e=>{if(!drag)return;if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();cancel();ctx.render();}else if(e.key.toLowerCase()==='r'){e.preventDefault();e.stopImmediatePropagation();ctx.rotate();paint(drag.x,drag.y);}else if(e.key.toLowerCase()==='f'){e.preventDefault();e.stopImmediatePropagation();ctx.noFlip();}},true);
 }
 window.DinoConstructionDrag={install};
})();
