/* Shared food and equipment crafting picker. app.js owns input; engine.js owns payment. */
(()=>{
 'use strict';
 const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const baked={fish:'cookedFish',meat:'cookedMeat',mushroom:'cookedMushroom'};
 function recipes(g){
  const E=window.DinoEngine,p=E.active(g),bag=p.bag.filter(i=>!i.topping),find=kind=>bag.find(i=>i.kind===kind),owned=kind=>bag.filter(i=>i.kind===kind).length;
  const list=Object.entries(baked).map(([raw,kind])=>({id:'cook-'+raw,group:'food',name:E.RES[kind].name,inputs:[[raw,1],['branch',1]],output:{kind,amount:1,food:E.foodValue({kind})},description:'원래 가방 자리에서 구운 면으로 뒤집습니다.',available:owned(raw)>0&&owned('branch')>0,type:'cook',data:{items:find(raw)?[find(raw).id]:[]}}));
  for(const r of E.FOOD_STACKS)list.push({id:'combine-'+r.id,group:'food',name:r.name,inputs:[[r.base,1],[r.topping,1]],output:{kind:r.base,topping:{kind:r.topping},amount:1,food:r.food},description:'두 재료를 한 칸에 겹칩니다. 빈칸으로 분리는 무료입니다.',available:owned(r.base)>0&&owned(r.topping)>0,type:'combineFood',data:{source:find(r.topping)?.id,target:find(r.base)?.id}});
  const spearReason=owned('spear')?'돌창은 1개까지 보유':'';
  list.push({id:'gear-spear',group:'gear',name:E.RES.spear.name,inputs:[['branch',1],['stone',1],['stem',1]],output:{kind:'spear',amount:1},benefit:'공격 +1 · 내구도 6',description:'공격할 때 공격력 +1. 내구도 6, 가방 3칸을 사용합니다. 자기 턴에 어디서든 조합합니다. 가방이 꽉 차면 임시 공간에 두고 가방을 정리한 뒤 무료로 옮기세요.',blockedReason:spearReason,available:!spearReason&&['branch','stone','stem'].every(k=>owned(k)>=1),type:'craft',data:{}});
  for(const [id,r]of Object.entries(E.AIRCRAFT_RECIPES)){const reason=p.pos!=='0,0'?'베이스캠프에서 제작':'';list.push({id:'aircraft-'+id,group:'aircraft',name:r.name,inputs:Object.entries(r.cost),output:{kind:r.results[0],amount:id==='steel'?1:r.results.length,...(id==='steel'?{steelShape:'L'}:{})},benefit:id==='steel'?'4칸 강철 조각 · 모양 선택':'공용 비행기 부품',description:'완성품은 임시 공간에서 가방으로 무료로 옮긴 뒤 캠프의 비행기에 설치하세요. 가방이 꽉 차도 제작할 수 있습니다.',blockedReason:reason,available:!reason&&Object.entries(r.cost).every(([k,n])=>owned(k)>=n),type:'aircraftCraft',normalOnly:true,data:{recipe:id}});}
  return list;
 }
 function batchRecipe(g,id,count=1,steelShape='L'){const E=window.DinoEngine,p=E.active(g),r=recipes(g).find(r=>r.id===id);if(!r)return null;if(id==='aircraft-steel'){const chosen=E.AIRCRAFT_STEEL_SHAPES.includes(steelShape)?steelShape:'L';return {...r,name:'강철판 '+chosen,output:{...r.output,amount:1,steelShape:chosen},data:{...r.data,steelShape:chosen},description:'4칸짜리 강철 한 조각을 만듭니다. 회전·뒤집기로 비행기의 부위 경계를 넘어 배치할 수 있습니다. 가방 공간이 부족하면 임시 공간에 보관합니다.'};}if(r.type!=='cook')return {...r,available:r.available&&count===1};const limit=p.pos==='0,0'?(p.boards.find(b=>b.id==='kitchen')?.complete?3:2):1,valid=Number.isInteger(count)&&count>=1&&count<=limit,raw=r.inputs[0][0],items=p.bag.filter(i=>i.kind===raw&&!i.topping).slice(0,valid?count:0).map(i=>i.id);return {...r,inputs:[[raw,count],['branch',1]],output:{...r.output,amount:count},data:{items},available:valid&&items.length===count&&p.bag.some(i=>i.kind==='branch'&&!i.topping)};}
 function render(g,ui,art){
  const E=window.DinoEngine,p=E.active(g),list=recipes(g),tab=ui.cookingTab||'food',base=list.find(r=>r.id===ui.cookingRecipe),limit=base?.type==='cook'&&p.pos==='0,0'?(p.boards.find(b=>b.id==='kitchen')?.complete?3:2):1;
  const count=Number.isInteger(ui.cookingCount)&&ui.cookingCount>=1&&ui.cookingCount<=limit?ui.cookingCount:1,chosen=base?batchRecipe(g,base.id,count,ui.steelShape):null;
  const cards=[...new Set(Array.isArray(ui.cookingCards)?ui.cookingCards:ui.selectedCard===null||ui.selectedCard===undefined?[]:[ui.selectedCard])].filter(i=>Number.isInteger(i)&&p.hand[i]!==undefined),cardAllowed=c=>!chosen?.normalOnly||!!E.CARDS[c]&&c!=='hunger',cardsValid=cards.every(i=>cardAllowed(p.hand[i]));
  const busy=!!(g.battle||g.huntResult||g.pendingDeparture||g.pendingEvent||g.pendingExplore||g.tileSetup||g.gathering||g.payment||g.pending?.length||g.loot?.length||g.ended||g.winner!==null);
  const owned=kind=>p.bag.filter(i=>i.kind===kind&&!i.topping).length,outcome=r=>r.output.topping||r.group!=='food'?art.itemShape(r.output,32):art.icon(r.output.kind,42),benefit=r=>r.group==='food'?'포만감 +'+r.output.food:r.benefit;
  const ingredient=([kind,n])=>`<span class="cooking-ingredient ${owned(kind)>=n?'enough':'short'}">${art.icon(kind,29)}<b>${esc(E.RES[kind].name)} ×${n}</b><small>보유 ${owned(kind)}</small></span>`;
  const row=r=>`<button class="cooking-recipe ${chosen?.id===r.id?'selected':''} ${r.available?'available':'unavailable'}" data-do="cooking-recipe" data-recipe-id="${esc(r.id)}" aria-pressed="${chosen?.id===r.id}" aria-label="${esc(r.name)} · ${esc(benefit(r))} · ${esc(r.blockedReason||(r.available?'재료 충족':'재료 부족'))}"><span class="cooking-row-title"><strong>${esc(r.name)}</strong><small>${esc(r.blockedReason||(r.available?'재료 충족':'재료 부족'))}</small></span><span class="cooking-equation"><span class="cooking-inputs">${r.inputs.map((input,i)=>(i?'<span class="cooking-plus" aria-hidden="true">+</span>':'')+ingredient(input)).join('')}</span><span class="cooking-arrow" aria-hidden="true">→</span><span class="cooking-output">${outcome(r)}<b>${esc(benefit(r))}</b><small>완성 ${r.output.amount}개</small></span></span></button>`;
  const reason=busy?'진행 중인 행동을 먼저 마쳐주세요.':g.actions<1?'남은 행동이 없습니다.':!chosen?'만들 물건을 골라주세요.':chosen.blockedReason?chosen.blockedReason:!chosen.available?'선택한 개수만큼 만들 재료가 부족합니다.':!cardsValid?'허기·퀘스트 대신 일반 손패를 선택해주세요.':cards.length!==count?`사용할 손패 ${count}장을 골라주세요.`:'재료를 지불 칸에 옮기면 완성됩니다.';
  const handCard=(c,i)=>{const selected=cards.includes(i),markup=art.cardMarkup(c,i).replace(/class="([^"]*\baction-card\b[^"]*)"/,(_,classes)=>`class="${classes.split(/\s+/).filter(c=>c&&c!=='selected').join(' ')}${selected?' selected':''}"`).replace(/aria-pressed="[^"]*"/,`aria-pressed="${selected}"`).replace('<button ',`<button ${cardAllowed(c)?'':'disabled '} `);return `<div class="cooking-card-wrap ${selected?'chosen':''}">${markup}${selected?`<span class="cooking-card-order" aria-hidden="true">${cards.indexOf(i)+1}</span>`:''}</div>`;};
  const quantities=chosen?.type==='cook'?`<div class="cooking-quantity"><strong>완성 개수</strong><div class="cooking-counts" role="group" aria-label="조리할 개수">${Array.from({length:limit},(_,i)=>`<button data-do="cooking-count" data-count="${i+1}" class="${count===i+1?'selected':''}" aria-pressed="${count===i+1}">${i+1}개</button>`).join('')}</div><small>${p.pos!=='0,0'?'탐험 중에는 한 개씩':limit===3?'야외 주방 · 한 번에 최대 3개':'기본 모닥불 · 한 번에 최대 2개'}</small></div>`:'';
  return `<div class="modal-scrim cooking-scrim"><section class="modal cooking-modal" role="dialog" aria-modal="true" aria-labelledby="cooking-title"><header class="modal-header"><div><div class="eyebrow">MAKE SOMETHING FOR THE JOURNEY</div><h2 id="cooking-title">무엇을 만들까요?</h2><p>음식·도구·장비 조합은 어디서든 · 비행기 부품 제작은 캠프에서</p></div><button class="close" data-do="close" aria-label="조리·조합 닫기">×</button></header><nav class="crafting-tabs" aria-label="제작 분류">${[['food','음식',8],['gear','무기·장비',1],['aircraft','비행기 부품',3]].map(([id,name,n])=>`<button data-do="cooking-tab" data-cooking-tab="${id}" class="${tab===id?'selected':''}" aria-pressed="${tab===id}">${name}<small>${n}</small></button>`).join('')}</nav><div class="cooking-layout"><div class="cooking-recipes" aria-label="조리·조합 목록">${tab==='food'?`<h3>${art.icon('fire',20)} 불에 굽기</h3>${list.filter(r=>r.type==='cook').map(row).join('')}<h3>${art.icon('herb',20)} 허브와 곁들이기</h3>${list.filter(r=>r.type==='combineFood').map(row).join('')}`:list.filter(r=>r.group===tab).map(row).join('')}</div><aside class="cooking-selection"><div class="eyebrow">이번에 만들 물건</div>${chosen?`<div class="cooking-selected-art">${outcome(chosen)}<b>×${chosen.output.amount}</b></div><h3>${esc(chosen.name)}</h3><p>${esc(chosen.description)}</p>${quantities}${chosen.id==='aircraft-steel'?`<div class="steel-shape-choice"><b>강철 모양 선택 · 모두 4칸</b><div>${E.AIRCRAFT_STEEL_SHAPES.map(shape=>`<button data-steel-shape="${shape}" class="${(ui.steelShape||'L')===shape?'selected':''}" aria-label="강철 ${shape} 모양">${art.itemShape({kind:'steel',steelShape:shape},22)}<span>${shape}</span></button>`).join('')}</div></div>`:''}<div class="cooking-selected-inputs">${chosen.inputs.map(input=>ingredient(input)).join('<span class="cooking-plus" aria-hidden="true">+</span>')}</div><div class="cooking-summary"><span>${art.icon(chosen.group==='food'?'berryTea':'hammer',20)} ${esc(benefit(chosen))}</span><span>${art.icon('card',20)} 손패 <b>${count}장</b></span><span>${art.icon('action',20)} 행동 <b>1회</b></span></div>`:'<div class="cooking-empty">'+art.icon(tab==='food'?'berryTea':'hammer',48)+'<p>조합에서 만들 물건을 골라주세요.</p></div>'}<div class="cooking-card-choice"><strong>사용할 손패 ${count}장</strong><small>${cards.length} / ${count}장 선택</small></div><div class="cooking-hand">${p.hand.map(handCard).join('')||'<p class="cooking-warning">손패가 없습니다.</p>'}</div><p class="cooking-status ${chosen&&!chosen.available||busy||g.actions<1?'short':''}" role="status">${reason}</p><button class="btn primary cooking-submit" data-do="cooking-submit" ${busy||g.actions<1||!chosen?.available||!cardsValid||cards.length!==count?'disabled':''}>재료 내고 만들기 →</button><p class="cooking-footnote">${chosen?.group==='food'?'음식마다 카드 1장 · 굽는 연료는 한 번에 가지 1개':chosen?.group==='gear'?'조합 1개 · 카드 1장과 행동 1회':'부품 제작 1회 · 카드 1장과 행동 1회'}<br>재료를 모두 내기 전에는 취소할 수 있습니다.</p></aside></div></section></div>`;
 }
 window.DinoCookingUI=Object.freeze({recipes,batchRecipe,render});
})();
