(function (root) {
  'use strict';
  const DETECTION_MAX=8,SHARED_DETECTION_MAX=12;
  const RES = {
    branch:{name:'나뭇가지',color:'#b5804a'},stone:{name:'돌',color:'#8b9b9c'},stem:{name:'줄기',color:'#a9b95a'},
    berry:{name:'산딸기',color:'#d9646c',food:1},mushroom:{name:'버섯',color:'#dcac64',food:1},water:{name:'맑은물',color:'#70bcd3',food:1},
    fish:{name:'물고기',color:'#64a5b1',food:1},herb:{name:'허브',color:'#70a77c'},metal:{name:'금속',color:'#7896a4'},
    meat:{name:'고기',color:'#c9776b',food:1},cookedFish:{name:'구운 물고기',color:'#d39450',food:3},cookedMeat:{name:'구운 고기',color:'#c47e4b',food:3},
    cookedMushroom:{name:'구운 버섯',color:'#b39557',food:2},berryTea:{name:'허브 산딸기차',color:'#ce8996',food:3},ration:{name:'비상식량',color:'#d8b967',food:3},
    battery:{name:'항공 배터리',color:'#c5aa67'},steel:{name:'강철판',color:'#889ca9'},engine:{name:'비행기 엔진',color:'#708b91'},cooler:{name:'냉각장치',color:'#71b6b5'},spear:{name:'돌창',color:'#ad9170'},knife:{name:'생존용 칼',color:'#839c9d'}
  };
  const TERRAIN={camp:{name:'베이스캠프',color:'#e3c28a'},forest:{name:'숲',color:'#98b88b'},bush:{name:'덤불',color:'#c0cc8a'},plain:{name:'평원',color:'#d9c589'},stream:{name:'시냇물',color:'#93c6c5'},cave:{name:'동굴',color:'#a6adb0'},escape:{name:'비상착륙장',color:'#d8b17e'}};
  const CARDS={explore:{name:'새로운 길',tag:'탐험',desc:'인접 지형 1장 공개 · 그 타일로 이동 선택',icon:'compass'},gather:{name:'숲의 선물',tag:'채집',desc:'자원 최대 3개 · 발각 +1',icon:'leaf'},run:{name:'가벼운 발걸음',tag:'달리기',desc:'공개 지형 최대 2칸 이동 · 발각 +1',icon:'boot'},hide:{name:'흔적 지우기',tag:'흔적 지우기',desc:'발각 −1 · 첫 인쇄 자원 1개를 현재 지형에 생성',icon:'eye'},harvest:{name:'한 아름',tag:'집중채집',desc:'현재 타일 자원 전부 · 발각 +2',icon:'basket'},hunger:{name:'허기',tag:'상태',desc:'이동·흔적 지우기용으로만 사용',icon:'empty'}};
  const COMBAT={punch:{name:'맨손 공격',atk:1,guard:0},crouch:{name:'웅크리기',atk:0,guard:1},strike:{name:'힘껏 치기',atk:2,guard:0},dodge:{name:'몸 낮추기',atk:0,guard:2}};
  const SHAPES={I:[[0,0],[1,0],[2,0],[3,0]],O:[[0,0],[1,0],[0,1],[1,1]],L:[[0,0],[0,1],[0,2],[1,2]],T:[[0,0],[1,0],[2,0],[1,1]],S:[[1,0],[2,0],[0,1],[1,1]],I3:[[0,0],[1,0],[2,0]],V3:[[0,0],[0,1],[1,1]],U5:[[0,0],[2,0],[0,1],[1,1],[2,1]],D:[[0,0]],D2:[[0,0],[1,0]],Z:[[0,0],[1,0],[1,1],[2,1]],J:[[0,0],[0,1],[1,1],[2,1]],Z5:[[1,0],[2,0],[1,1],[0,2],[1,2]]};
  const MATERIALS={wood:{name:'목재',color:'#cb9b63',raw:'branch',shapes:['D','D2','V3','Z','U5']},stone:{name:'돌블록',color:'#8caaae',raw:'stone',shapes:['D','D2','J','S','O']},fiber:{name:'엮은 섬유',color:'#a6bb74',raw:'stem',shapes:['D','D2','T','Z5']}};
  const PIECE_RECIPES=Object.entries({wood:{D:2,D2:3,V3:3,Z:4,U5:3},stone:{D:2,D2:3,J:4,S:4,O:5},fiber:{D:2,D2:3,T:4,Z5:3}}).flatMap(([material,recipes])=>Object.entries(recipes).map(([shape,cost])=>({material,shape,cost,craftable:true,max:3})));
  // Retired pieces remain movable in existing saves, but cannot be manufactured.
  const RETIRED_PIECES={wood:['I','I3','T','L','S'],fiber:['S']};
  const retiredPiece=piece=>!!RETIRED_PIECES[piece?.material]?.includes(piece?.shape);
  const pieceRecipe=(material,shape)=>PIECE_RECIPES.find(r=>r.material===material&&r.shape===shape);
  const pieceCost=(material,shape)=>pieceRecipe(material,shape)?.cost??null;
  function allPieces(g){return [...new Map([...(g.pending||[]),...g.players.flatMap(p=>[...(p.boards||[]),...(p.storage||[])].flatMap(b=>b.cells||[]).filter(Boolean))].map(p=>[p.id,p])).values()];}
  function pieceStock(g,material,shape){const recipe=pieceRecipe(material,shape);if(!recipe)return retiredPiece({material,shape})?Math.max(0,3-allPieces(g).filter(p=>p.material===material&&p.shape===shape).length):0;const stored=g.pieceSupply?.[`${material}:${shape}`];return Number.isInteger(stored)?Math.max(0,Math.min(recipe.max,stored)):Math.max(0,recipe.max-allPieces(g).filter(p=>p.material===material&&p.shape===shape).length);}
  function restorePieceSupply(g){g.pieceSupply=Object.fromEntries(PIECE_RECIPES.map(r=>[`${r.material}:${r.shape}`,pieceStock(g,r.material,r.shape)]));}
  function takePiece(g,material,shape){const available=pieceStock(g,material,shape);assert(available>0,'해당 모양의 공용 자재 조각이 모두 사용 중입니다.');g.pieceSupply[`${material}:${shape}`]=available-1;return {id:uid(g),material,shape,rotation:0,flip:false};}
  function returnPiece(g,piece){const recipe=pieceRecipe(piece.material,piece.shape);if(!recipe)return;const occupied=allPieces(g).filter(p=>p.material===piece.material&&p.shape===piece.shape).length;g.pieceSupply[`${piece.material}:${piece.shape}`]=Math.max(0,Math.min(recipe.max-occupied,pieceStock(g,piece.material,piece.shape)+1));}
  function boardMask(b){return Array.isArray(b.mask)?b.mask:Array(b.w*b.h).fill(true);}
  function boardLevels(b){return (b.zones||[]).map(zone=>{const indices=zone.indices.slice(),counts={};let filled=0;for(const index of indices){const cell=b.cells[index];if(cell){filled++;counts[cell.material]=(counts[cell.material]||0)+1;}}return {...zone,indices,needs:{...zone.needs},unlock:(zone.unlock||[]).slice(),counts,filled,total:indices.length,ready:filled===indices.length&&Object.entries(zone.needs).every(([kind,amount])=>(counts[kind]||0)===amount)};});}
  function restoreBuildings(g){
    for(const p of g.players){
      p.boards=p.boards||[];for(const b of p.boards)if(b.id==='workshop')b.desc=BUILDINGS.find(def=>def.id==='workshop').desc;const packIds=['pack1','pack2','pack3'],packs=p.boards.filter(b=>packIds.includes(b.id)),hasLevels=packs.some(b=>b.id==='pack1'&&Array.isArray(b.zones));
      if(!hasLevels){
        const started=packs.some(b=>b.legacyPack||b.complete||b.cells?.some(Boolean)||b.bonuses?.some(b=>b.claimed))||bagUnlocked(p).length>0||Number(p.capacity)>12;
        if(started){for(const b of packs)b.legacyPack=true;const groups=bagUnlocked(p).slice(),capacityGroups=Math.max(0,Math.min(3,Math.floor((Number(p.capacity)-12)/3)));for(const group of BAG.groups)if(groups.length<capacityGroups&&!groups.includes(group))groups.push(group);if(groups.length!==bagUnlocked(p).length)p.bagUnlocks=groups;}
        else{const at=p.boards.findIndex(b=>packIds.includes(b.id)),def=BUILDINGS.find(b=>b.id==='pack1');p.boards=p.boards.filter(b=>!packIds.includes(b.id));p.boards.splice(at<0?0:at,0,{...clone(def),cells:Array(def.w*def.h).fill(null),complete:false});}
      }
      for(let i=0;i<p.boards.length;i++){const old=p.boards[i],def=BUILDINGS.find(b=>b.id===old.id);if(def&&!old.legacyPack&&!Array.isArray(old.zones)&&!old.complete&&!old.cells?.some(Boolean)&&!old.bonuses?.some(b=>b.claimed))p.boards[i]={...clone(def),cells:Array(def.w*def.h).fill(null),complete:false};}
    }
  }
  function completeBoardLevels(g,p,b){
    const levels=boardLevels(b),allReady=levels.every(zone=>zone.ready);
    for(const level of levels){if(level.active||!level.ready||level.level>1&&!allReady)continue;const zone=b.zones.find(z=>z.id===level.id);zone.active=true;p.bagUnlocks=bagUnlocked(p).slice();for(const group of zone.unlock||[])if(!p.bagUnlocks.includes(group))p.bagUnlocks.push(group);p.capacity=12+p.bagUnlocks.length*3;p.vp+=zone.vp||0;log(g,`${p.name} · ${b.name} ${zone.name} 완성! 가방 ${p.capacity}칸 · +${zone.vp||0}점`,'good');}
    b.complete=allReady&&boardMask(b).every((used,i)=>!used||b.cells[i]);
  }
  function claimBoardBonuses(g,p,b,piece){for(const bonus of b.bonuses||[]){if(bonus.claimed||b.cells[bonus.y*b.w+bonus.x]?.id!==piece.id)continue;bonus.claimed=true;if(bonus.type==='berries'){gain(g,p,Array(bonus.amount).fill('berry'));log(g,`${b.name} 칸 보너스 · 산딸기 ${bonus.amount}개`,'good');}else if(bonus.type==='piece'){if(pieceStock(g,bonus.material,bonus.shape)>0){g.pending.push(takePiece(g,bonus.material,bonus.shape));log(g,`${b.name} 칸 보너스 · ${MATERIALS[bonus.material].name} ${bonus.shape} 조각 1개 · 즉시 배치`,'good');}else{gain(g,p,['berry']);log(g,`${b.name} 칸 보너스 · ${MATERIALS[bonus.material].name} ${bonus.shape} 재고 없음 → 산딸기 1개`,'good');}}}}
  const BUILDINGS=[{"id":"pack1","name":"배낭 작업대","w":10,"h":2,"needs":{"wood":12,"fiber":4},"vp":3,"desc":"1레벨: 위쪽 +3칸 · 2레벨: 양옆 +6칸 (최대 21칸)","effect":"pack","mask":[false,true,true,true,true,true,true,true,true,false,true,true,true,true,false,false,true,true,true,true],"zones":[{"id":"pack-level-1","level":1,"name":"1레벨","indices":[1,2,3,4,10,11,12,13],"needs":{"wood":8},"unlock":["top"],"vp":1,"active":false},{"id":"pack-level-2","level":2,"name":"2레벨","indices":[5,6,7,8,16,17,18,19],"needs":{"wood":4,"fiber":4},"unlock":["left","right"],"vp":2,"active":false}],"bonuses":[{"id":"pack1-berries","x":4,"y":0,"type":"berries","kind":"berry","amount":2,"claimed":false},{"id":"pack2-berries","x":8,"y":0,"type":"berries","kind":"berry","amount":2,"claimed":false}]},{"id":"kitchen","name":"야외 주방","w":4,"h":4,"needs":{"wood":8,"stone":4},"vp":2,"desc":"조리 한 번에 최대 3개","effect":"kitchen","mask":[false,true,true,false,true,true,true,true,true,true,true,true,false,true,true,false],"bonuses":[{"id":"kitchen-berries","x":2,"y":0,"type":"berries","kind":"berry","amount":2,"claimed":false},{"id":"kitchen-piece","x":1,"y":3,"type":"piece","material":"wood","shape":"D","claimed":false}]},{"id":"workshop","name":"장비 공방","w":5,"h":4,"needs":{"wood":8,"fiber":8},"vp":2,"desc":"완성 승점 2 · V3 조각·산딸기 보상 칸","effect":"workshop","mask":[false,true,true,true,false,true,true,true,true,true,true,true,false,true,true,false,true,true,true,true],"bonuses":[{"id":"workshop-piece","x":4,"y":1,"type":"piece","material":"wood","shape":"V3","claimed":false},{"id":"workshop-berries","x":1,"y":3,"type":"berries","kind":"berry","amount":2,"claimed":false}]},{"id":"warehouse","name":"자재 창고","w":3,"h":3,"needs":{"wood":8},"vp":1,"desc":"추가 4×4 자재 보관소","effect":"warehouse","mask":[true,true,true,true,false,true,true,true,true],"bonuses":[{"id":"warehouse-piece","x":1,"y":0,"type":"piece","material":"wood","shape":"D","claimed":false}]}];
  const PREY={
    deer:{name:'노루',hp:[3,5],atk:[1,2],pattern:['C','B','?'],actionNames:{A:'뒷발 차기',B:'몸 낮추기',C:'밀치기'},ABC:[{A:['attack',2],B:['guard',1],C:['attack',1]},{A:['attack',3],B:['guard',2],C:['attack',2]}],skill:'평원에서 조우했다면, 자신의 행동 시작 시 HP 1 이하에서 다른 지형으로 최대 2칸 도망갑니다.',loot:['meat','meat','herb']},
    boar:{name:'멧돼지',hp:[5,7],atk:[1,2],pattern:['B','C','?'],actionNames:{A:'들이박기',B:'준비하기',C:['도망치기','웅크리기']},ABC:[{A:['attack',1],B:['prepare',1],C:['flee',1]},{A:['attack',2],B:['prepare',1],C:['guard',2]}],skill:'HP가 절반 이하이면 모든 공격에 +1을 더합니다.',loot:['meat','meat','meat']},
    turtle:{name:'큰 거북',hp:[4,6],atk:[1,1],pattern:['C','B','?'],actionNames:{A:'세게 물기',B:'등딱지 숨기',C:'물기'},ABC:[{A:['attack',2],B:['guard',2],C:['attack',1]},{A:['attack',3],B:['guard',3],C:['attack',2]}],skill:'공격력 3 이상의 공격을 받으면 피해를 1 줄입니다.',loot:['meat','stone','stone']}
  };
  function battlePattern(b){return Array.isArray(b?.pattern)&&b.pattern.length===3?b.pattern:PREY[b?.kind]?.pattern||['A','B','?'];}
  function preyAction(kind,level,letter){const m=PREY[kind],move=m?.ABC[level-1]?.[letter];if(!move)return null;const names=m.actionNames?.[letter],name=Array.isArray(names)?names[level-1]:names;const [type,value]=move;return {letter,type,value,name:name||({attack:'공격',guard:'방어',prepare:'준비하기',flee:'도망치기'})[type],effect:type==='attack'?`공격 ${value}`:type==='guard'?`다음 공격 방어 ${value}`:type==='prepare'?`다음 공격 +${value}`:`다른 지형으로 ${value}칸 이동`};}
  function battleAction(b,index=b.step){const pattern=battlePattern(b),mark=pattern[index],unknown=mark==='?',orderIndex=pattern.slice(0,index+1).filter(v=>v==='?').length-1,letter=unknown?b.order?.[orderIndex]:mark;return {...(preyAction(b.kind,b.level,letter)||{letter:null,type:'unknown',value:0,name:'미공개',effect:'행동 카드에서 결정'}),unknown,index};}
  const DINOS=[{id:'tyranno',name:'티라노',terrain:'plain',A:'고기가 가장 많은 탐험가',B:'가장 가까운 탐험가',C:'비상착륙장에 가장 가까운 탐험가',D:'넘어짐 · 1회 대기'},
    {id:'spino',name:'스피노사우루스',terrain:'stream',A:'물고기가 가장 많은 탐험가',B:'물가의 가장 가까운 탐험가',C:'가장 가까운 탐험가',D:'물 마시기 · 1회 대기'},
    {id:'allo',name:'알로사우루스',terrain:'forest',A:'체력이 가장 낮은 탐험가',B:'발각률이 가장 높은 탐험가',C:'가장 가까운 탐험가',D:'주변 경계 · 1회 대기'}];
  const DIR=[[1,0],[1,-1],[0,-1],[-1,0],[-1,1],[0,1]];
  const key=(q,r)=>`${q},${r}`;
  const pos=k=>k.split(',').map(Number);
  const dist=(a,b)=>{const [q,r]=pos(a),[x,y]=pos(b);return (Math.abs(q-x)+Math.abs(r-y)+Math.abs(q+r-x-y))/2;};
  const neighbors=k=>{const [q,r]=pos(k);return DIR.map(([a,b])=>key(q+a,r+b));};
  const clone=x=>JSON.parse(JSON.stringify(x));
  const assert=(v,m)=>{if(!v)throw new Error(m);};
  const active=g=>g.players[g.turn];
  function rng(g){let x=g.seed|0;x^=x<<13;x^=x>>>17;x^=x<<5;g.seed=x>>>0;return g.seed/4294967296;}
  function shuffle(g,a){a=a.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(rng(g)*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
  const uid=g=>`i${g.serial++}`;
  const BASIC_DECK=['explore','explore','explore','explore','gather','gather','gather','gather','run','hide','hide','harvest'];
  function log(g,text,type='note'){g.log.unshift({text,type,round:g.round});g.log=g.log.slice(0,100);}
  const BAG={width:5,height:5,groups:['top','left','right'],cells:[]};
  for(let y=0;y<5;y++)for(let x=0;x<5;x++){if(y<2&&(x===0||x===4))continue;BAG.cells.push({x,y,group:y===0?'top':x===0?'left':x===4?'right':null});}
  function transformCells(cells,rot=0,flip=false){let c=cells.map(([x,y])=>[flip?-x:x,y]);for(let i=0;i<(rot%4+4)%4;i++)c=c.map(([x,y])=>[-y,x]);const x=Math.min(...c.map(v=>v[0])),y=Math.min(...c.map(v=>v[1]));return c.map(([a,b])=>[a-x,b-y]);}
  function shape(s,rot=0,flip=false){return transformCells(SHAPES[s],rot,flip);}
  function bagUnlocked(p){return p.bagUnlocks||BAG.groups.slice(0,Math.max(0,Math.min(3,(p.capacity-12)/3)));}
  function bagCells(p){const groups=bagUnlocked(p);return BAG.cells.map(c=>({...c,locked:!!c.group&&!groups.includes(c.group)}));}
  function itemCells(i){const cells=i.kind==='steel'&&i.steelShape?SHAPES[i.steelShape]:i.kind==='engine'?[[0,0],[1,0],[0,1],[1,1]]:i.kind==='cooler'?[[0,0],[1,0]]:i.kind==='battery'?[[0,0],[0,1],[1,1]]:i.kind==='spear'?[[0,0],[0,1],[0,2]]:['knife','ration'].includes(i.kind)?[[0,0],[0,1]]:[[0,0]];return transformCells(cells,i.rotation||0,!!i.flip);}
  function occupied(p,except){const s=new Set();for(const i of p.bag)if(i.id!==except)for(const [x,y]of itemCells(i))s.add(key(i.x+x,i.y+y));return s;}
  function bagFits(p,i,x,y){if(!Number.isInteger(x)||!Number.isInteger(y))return false;const used=occupied(p,i.id),open=new Set(bagCells(p).filter(c=>!c.locked).map(c=>key(c.x,c.y)));return itemCells(i).every(([a,b])=>open.has(key(x+a,y+b))&&!used.has(key(x+a,y+b)));}
  function findBagSpace(p,i,rotate=false){for(const rotation of rotate?[...new Set([i.rotation||0,0,1,2,3])]:[i.rotation||0])for(const flip of rotate?[!!i.flip,!i.flip]:[!!i.flip]){const candidate={...i,rotation,flip};for(const cell of bagCells(p).filter(c=>!c.locked))if(bagFits(p,candidate,cell.x,cell.y))return {...candidate,x:cell.x,y:cell.y};}return null;}
  const canFitItem=(p,item)=>!!p&&!!RES[item?.kind]&&!!findBagSpace(p,item,true);
  const groundItems=(g,tile)=>g.tiles[tile]?.groundItems||[];
  function printedResources(t){if(Array.isArray(t?.resourcePlan))return t.resourcePlan.slice();if(Array.isArray(t?.claims))return t.claims.map(v=>typeof v==='string'?v:v?.kind).filter(k=>RES[k]);const original=(root.DINO_TERRAIN||[]).find(v=>v.id===t?.id);if(!original)return [];const printed=original.resources.slice();if(t.level===2){const at=printed.findIndex(k=>['stone','stem','branch'].includes(k));if(at>=0)printed[at]='metal';}return printed;}
  function traceResource(t){const first=printedResources(t)[0];return RES[first]?first:null;}
  const tileResourceCount=t=>(t?.resources?.length||0)+(t?.groundItems?.length||0);
  const allGroundItems=g=>Object.values(g.tiles||{}).flatMap(t=>t.groundItems||[]);
  function lootOrigin(g,item){const owner=g.players.find(p=>p.id===item.owner);return g.tiles[item.origin]?item.origin:g.tiles[owner?.pos]?owner.pos:'0,0';}
  function leaveOnGround(g,item,origin=lootOrigin(g,item)){assert(g.tiles[origin],'물건을 남길 획득 지형이 없습니다.');const left={...item,origin};delete left.owner;if(left.source==='crafted')delete left.source;const tile=g.tiles[origin];tile.groundItems=tile.groundItems||[];assert(!tile.groundItems.some(i=>i.id===left.id),'이미 현장에 남겨둔 물건입니다.');tile.groundItems.push(left);return left;}
  function settleLootOverflow(g){const waiting=[];for(const item of g.loot){const owner=g.players.find(p=>p.id===item.owner)||active(g);if(item.source==='crafted'||canFitItem(owner,item))waiting.push(item);else{const origin=lootOrigin(g,item);leaveOnGround(g,item,origin);log(g,`${owner.name}의 가방에 ${itemName(item)} 모양이 들어가지 않아 ${TERRAIN[g.tiles[origin].terrain].name}에 남겼습니다.`);}}g.loot=waiting;}
  function canGatherFit(g){const p=active(g),s=g.gathering,t=g.tiles[s?.tile];return !!s&&s.player===p.id&&s.tile===p.pos&&!!t&&[...(t.resources||[]).map(kind=>({kind})),...(t.groundItems||[])].some(item=>canFitItem(p,item));}
  function canFinishGather(g){const p=active(g),s=g.gathering;return !!s&&s.player===p.id&&s.tile===p.pos&&(!s.paid||!s.all||!tileResourceCount(g.tiles[s.tile])||!canGatherFit(g));}
  // Setup/migration helper only. Gameplay gains remain in the manual placement queue.
  function addItem(g,p,kind){const i=makeItem(g,kind),fit=findBagSpace(p,i,true);if(!fit)return false;p.bag.push(fit);return true;}
  const count=(p,kind)=>p.bag.filter(i=>i.kind===kind&&!i.topping).length;
  const hasCost=(p,cost)=>Object.entries(cost).every(([k,n])=>count(p,k)>=n);
  function draw(g,p,n=4,combat=false){let deck=combat?'combatDeck':'deck',hand=combat?'combatHand':'hand',discard=combat?'combatDiscard':'discard';while(p[hand].length<n){if(!p[deck].length){if(!p[discard].length&&combat&&g.battle?.spent.length){p[discard].push(...g.battle.spent);g.battle.spent=[];log(g,'전투 덱이 비어 해결한 사용 카드를 다시 섞었습니다.');}if(!p[discard].length)break;p[deck]=shuffle(g,p[discard]);p[discard]=[];}p[hand].push(p[deck].pop());}}
  function cardData(c){return CARDS[c]||{name:'미완료 퀘스트',tag:'퀘스트',desc:'이동·흔적 지우기용으로 사용 가능',icon:'map'};}
  function validTurn(g,allowPending=false){assert(g.winner===null&&!g.ended,'이 원정은 종료되었습니다.');assert(!g.battle,'먼저 사냥을 마쳐주세요.');assert(!g.huntResult,'사냥 성공과 전리품을 먼저 확인해주세요.');if(!allowPending){assert(!g.pending.length,'만든 자재를 먼저 배치하거나 버려주세요.');assert(!g.loot.length,'획득한 물건의 가방 배치를 먼저 해결해주세요.');}}
  function spend(g,indices,n=1,normal=false){const p=active(g);assert(g.actions>=n,'남은 행동이 없습니다.');assert(indices.length&&new Set(indices).size===indices.length,'사용할 손패를 선택해주세요.');assert(indices.every(i=>Number.isInteger(i)&&i>=0&&i<p.hand.length),'선택한 카드가 손패에 없습니다.');if(normal)assert(indices.every(i=>CARDS[p.hand[i]]&&p.hand[i]!=='hunger'),'허기와 퀘스트 카드는 가공에 사용할 수 없습니다.');const cards=indices.map(i=>p.hand[i]);indices.slice().sort((a,b)=>b-a).forEach(i=>p.hand.splice(i,1));p.discard.push(...cards);g.actions-=n;return cards;}
  function card(g,index,type){assert(active(g).hand[index]===type,`${CARDS[type].tag} 카드를 선택해주세요.`);}
  function makeItem(g,kind,extra={}){const i={id:uid(g),kind,rotation:0,flip:false,...extra};if(['knife','spear'].includes(kind)&&i.durability===undefined)i.durability=6;return i;}
  function gain(g,p,kinds,extra={}){g.loot.push(...kinds.map(kind=>makeItem(g,kind,{owner:p.id,origin:p.pos,...extra})));}
  function lootOwner(g){return g.players.find(p=>p.id===g.loot[0]?.owner)||active(g);}
  function newGame({players=4,seed=20260917,names=[]}={},terrain=[]){const g={version:2,basicDeckRevision:2,seed:seed>>>0||1,serial:1,turn:0,round:1,actions:2,sharedDetection:0,players:[],tiles:{},terrainDeck:[],actionDeck:[],actionDiscard:[],preyDeck:[],events:[],eventDiscard:[],pendingEvent:null,log:[],dino:null,battle:null,battleEffect:null,huntResult:null,combatTurnEnd:null,pendingExplore:null,pendingDeparture:null,tileSetup:null,gathering:null,payment:null,pending:[],loot:[],pieceSupply:{},aircraft:null,winners:[],winner:null,ended:false,discoveries:0,lastActionCard:null,setupDecks:[]};
    const colors=['#df8b63','#63a997','#ba9ccd','#e3bc5c'],defs=['솔','이슬','노을','여울'];
    for(let i=0;i<Math.max(1,Math.min(4,players));i++){const p={id:i,name:(names[i]||defs[i]).slice(0,12),color:colors[i],pos:'0,0',pendingHunt:null,hp:8,hunger:6,detection:0,vp:0,capacity:12,bagUnlocks:[],bag:[],hand:[],deck:shuffle(g,BASIC_DECK),discard:[],combatHand:['punch','crouch','strike','punch'],combatDeck:shuffle(g,['punch','punch','crouch','crouch','strike','dodge']),combatDiscard:[],quests:[],surveyed:false,boards:BUILDINGS.map(b=>({...clone(b),cells:Array(b.w*b.h).fill(null),complete:false})),storage:[{id:'storage',name:'기본 보관소',w:3,h:3,cells:Array(9).fill(null)}]};g.players.push(p);g.setupDecks.push(p.deck.slice());draw(g,p);}
    restorePieceSupply(g);g.aircraft=createAircraft(g.players);
    g.tiles['0,0']={id:'base',terrain:'camp',level:1,resourcePlan:[],resources:[],groundItems:[],safe:true,hunt:null,event:false};
    let pool=terrain.length?clone(terrain):Array.from({length:35},(_,i)=>({id:`T${i}`,terrain:['forest','bush','plain','stream','cave'][i%5],resources:[['branch','branch','berry','herb'],['stem','stem','branch','berry'],['stone','stone','branch','berry'],['water','fish','water','herb'],['stone','stone','metal','mushroom']][i%5].slice(),event:i>29}));
    g.terrainDeck=shuffle(g,pool);g.terrainDeck.splice(Math.max(0,g.terrainDeck.length-8),0,{id:'exit',terrain:'escape',resources:[],event:false});
    g.events=shuffle(g,['ration','knife','questSupply','questWater','battery']);g.preyDeck=shuffle(g,['deer','deer','boar','boar','turtle','turtle']);
    for(const order of ['ABC','ACB','BAC','BCA','CAB','CBA'])for(const giant of 'ABCD')g.actionDeck.push({order,giant});g.actionDeck=shuffle(g,g.actionDeck);
    log(g,'원정 시작. 공용 비행기를 완성하고 모두 베이스캠프로 돌아오세요. 출발할 때 기존 점수와 조립 공헌을 합산합니다.','good');return g;}
  function routes(g,start,max=1,dino=false){const found={[start]:[]},q=[start];while(q.length){const k=q.shift();if(found[k].length>=max)continue;for(const n of neighbors(k)){if(!g.tiles[n]||found[n]!==undefined||(dino&&g.tiles[n].safe))continue;found[n]=[...found[k],n];q.push(n);}}return found;}
  function capacityOK(g,k,p=active(g)){return g.tiles[k]?.safe||g.players.filter(v=>v.id!==p.id&&v.pos===k).length<2;}
  function exploreTargets(g){const p=active(g);return neighbors(p.pos).filter(k=>!g.tiles[k]);}
  function takeActionCard(g){if(!g.actionDeck.length){g.actionDeck=shuffle(g,g.actionDiscard);g.actionDiscard=[];}const c=g.actionDeck.pop();g.actionDiscard.push(c);g.lastActionCard=c;return c;}
  function sharedDetectionValue(g){const value=Number.isFinite(g.sharedDetection)?g.sharedDetection:g.players.reduce((n,p)=>n+(Number(p.detection)||0),0);return Math.max(0,Math.min(SHARED_DETECTION_MAX,value));}
  function checkDetection(g,p=active(g)){if(!g.dino&&!g.ended&&g.winner===null&&(sharedDetectionValue(g)>=SHARED_DETECTION_MAX||g.players.some(x=>x.detection>=DETECTION_MAX))){const trigger=g.tiles[p.pos]?.safe?fieldPlayers(g)[0]:p;if(trigger)spawnDino(g,trigger);}}
  function detect(g,amount,p=active(g)){const shared=sharedDetectionValue(g);p.detection=Math.max(0,Math.min(DETECTION_MAX,p.detection+amount));g.sharedDetection=Math.max(0,Math.min(SHARED_DETECTION_MAX,shared+amount));checkDetection(g,p);}
  function fieldPlayers(g){return g.players.filter(p=>!g.tiles[p.pos].safe);}
  function spawnDino(g,trigger){if(g.dino||g.ended||g.winner!==null)return;let targets=fieldPlayers(g);if(!targets.length)return;const spec=DINOS[Math.floor(rng(g)*DINOS.length)];let near=Object.keys(g.tiles).filter(k=>!g.tiles[k].safe&&dist(k,trigger.pos)>0&&dist(k,trigger.pos)<=3);if(!near.length)near=Object.keys(g.tiles).filter(k=>!g.tiles[k].safe);let preferred=near.filter(k=>g.tiles[k].terrain===spec.terrain);const choices=preferred.length?preferred:near;if(!choices.length)return;const at=choices[Math.floor(rng(g)*choices.length)];targets.sort((a,b)=>dist(at,a.pos)-dist(at,b.pos)||a.id-b.id);g.dino={...spec,pos:at,target:targets[0].id,phase:0,last:'등장'};log(g,`${spec.name} 등장! ${targets[0].name}을 추격합니다. 최초 위치는 ${TERRAIN[g.tiles[at].terrain].name}.`,'danger');}
  function chooseTarget(g,letter){const d=g.dino;let list=fieldPlayers(g);if(!list.length)return null;const closest=(a,b)=>dist(d.pos,a.pos)-dist(d.pos,b.pos)||a.id-b.id;list.sort(closest);
    if(d.id==='tyranno'){if(letter==='A')list.sort((a,b)=>(materialCount(b,'meat')+materialCount(b,'cookedMeat'))-(materialCount(a,'meat')+materialCount(a,'cookedMeat'))||closest(a,b));if(letter==='C'){const exit=Object.keys(g.tiles).find(k=>g.tiles[k].terrain==='escape');if(exit)list.sort((a,b)=>dist(a.pos,exit)-dist(b.pos,exit)||closest(a,b));}}
    if(d.id==='spino'){if(letter==='A')list.sort((a,b)=>(materialCount(b,'fish')+materialCount(b,'cookedFish'))-(materialCount(a,'fish')+materialCount(a,'cookedFish'))||closest(a,b));if(letter==='B'){const water=list.filter(p=>g.tiles[p.pos].terrain==='stream');if(water.length)list=water;}}
    if(d.id==='allo'){if(letter==='A')list.sort((a,b)=>a.hp-b.hp||closest(a,b));if(letter==='B')list.sort((a,b)=>b.detection-a.detection||closest(a,b));}return list[0];}
  function dinosaurTurn(g){if(!g.dino)return;const d=g.dino;let target=g.players[d.target];if(!target||g.tiles[target.pos].safe)target=chooseTarget(g,'B');let wait=false;if(d.phase===2){const c=takeActionCard(g);wait=c.giant==='D';d.last=c.giant;if(!wait)target=chooseTarget(g,c.giant);log(g,`${d.name} 행동 ${c.giant} · ${wait?d.D:target?target.name+' 추격':'필드에 대상 없음'}`,'danger');}else d.last='추격';d.target=target?.id??null;
    if(target&&!wait){const path=routes(g,d.pos,80,true)[target.pos];if(path?.length)d.pos=path[0];}
    // 피해는 이동/대기 여부와 무관하게 공룡 행동 종료 시 한 번만 적용.
    for(const p of g.players)if(p.pos===d.pos&&!g.tiles[p.pos].safe){p.hp--;log(g,`${p.name}, 공룡과 같은 칸 · 체력 −1`,'danger');if(p.hp<=0)rescue(g,p);}
    d.phase=(d.phase+1)%3;
  }
  function rescue(g,p){const tile=g.tiles[p.pos];g.loot=g.loot.filter(i=>{if(i.owner===p.id&&!['spear','knife'].includes(i.kind)){leaveOnGround(g,i);return false;}return true;});for(const i of p.bag)if(!['spear','knife'].includes(i.kind))tile.resources.push(...itemParts(i).map(part=>part.kind));p.bag=p.bag.filter(i=>['spear','knife'].includes(i.kind));p.pos='0,0';p.pendingHunt=null;p.hp=8;p.hunger=6;p.vp=Math.max(0,p.vp-2);p.detection=0;log(g,`${p.name} 기절. 자원을 현장에 남기고 캠프로 구조 · HP 8 / 포만감 6 / 발각 0 / 승점 −2`,'danger');}
  function quests(g,p){for(const q of p.quests.filter(q=>!q.done))if(q.type==='water'&&g.tiles[p.pos].terrain==='stream'&&q.start!==p.pos){detect(g,-2,p);completeQuest(g,p,q);}}
  const EVENT_CARDS={
    ration:{name:'먼지 쌓인 비상식량함',text:'비상식량 카드 1장을 얻습니다. 공용 타일 주머니에서 2칸 직선 블록을 꺼내 가방에 놓으세요. 포만감 +3.',kind:'item',reward:'ration',icon:'ration'},
    knife:{name:'주인 없는 배낭',text:'생존용 칼 카드 1장을 얻습니다. 공용 타일 주머니에서 두 칸 블록을 꺼내 가방에 놓으세요.',kind:'item',reward:'knife',icon:'knife'},
    battery:{name:'예비 항공 배터리',text:'항공 배터리 카드 1장을 얻습니다. 공용 타일 주머니에서 L자 세 칸 블록을 꺼내 가방에 놓으세요.',kind:'item',reward:'battery',icon:'battery'},
    questSupply:{name:'정비사의 채집 메모',text:'캠프에 나뭇가지·돌·줄기를 하나씩 반납하세요. 완료하면 2점과 집중채집 카드를 얻습니다.',kind:'quest',reward:null,icon:'map'},
    questWater:{name:'갈대숲의 피난 지도',text:'다른 시냇물 지형에 도착하세요. 완료하면 2점을 얻고 발각률을 2 낮춥니다.',kind:'quest',reward:null,icon:'map'}
  };
  function event(g,t){if(!t.event||t.eventDone)return;assert(!g.pendingEvent,'진행 중인 이벤트를 먼저 확인해주세요.');g.pendingEvent={player:active(g).id,tile:active(g).pos,stage:'draw',card:null};log(g,'이벤트 장소 발견 · 이벤트 덱에서 카드 한 장을 뒤집어주세요.');}
  function currentEvent(g,stage){validTurn(g,true);const pending=g.pendingEvent,p=active(g),tile=g.tiles[pending?.tile];assert(pending&&pending.player===p.id&&pending.tile===p.pos&&tile?.event&&!tile.eventDone,'확인할 이벤트가 없습니다.');assert(pending.stage===stage,stage==='draw'?'이미 이벤트 카드를 뒤집었습니다.':'먼저 이벤트 카드를 뒤집어주세요.');assert(!g.pendingExplore&&!g.tileSetup&&!g.gathering&&!g.payment&&!g.pending.length,'진행 중인 행동을 먼저 마쳐주세요.');return {pending,p,tile};}
  function drawEvent(g){const {pending}=currentEvent(g,'draw');if(!g.events.length){assert(g.eventDiscard.length,'뒤집을 이벤트 카드가 없습니다.');g.events=shuffle(g,g.eventDiscard);g.eventDiscard=[];}const card=g.events.pop();assert(EVENT_CARDS[card],'알 수 없는 이벤트 카드입니다.');pending.card=card;pending.stage='revealed';g.lastEvent=card;log(g,`이벤트 카드 공개 · ${EVENT_CARDS[card].name}`);}
  function resolveEvent(g){const {pending,p,tile}=currentEvent(g,'revealed'),id=pending.card,card=EVENT_CARDS[id];assert(card,'확인할 이벤트 카드가 없습니다.');if(card.kind==='item'){gain(g,p,[card.reward]);log(g,`${card.name} · ${RES[card.reward].name} 획득 · 가방에 직접 배치하세요.`,'good');}else{const q={id:uid(g),type:id==='questSupply'?'supply':'water',name:card.name,start:p.pos,done:false};p.quests.push(q);p.discard.push(`quest:${q.id}`);log(g,`${q.name} · 퀘스트가 행동 덱에 추가되었습니다.`);}g.eventDiscard.push(id);tile.eventDone=true;g.pendingEvent=null;encounter(g,tile);}
  function encounter(g,t,optional=false){
    if(!t.hunt)return;const p=active(g);let kind=t.hunt.kind;
    if(!kind){if(!g.preyDeck.length)g.preyDeck=shuffle(g,Object.keys(PREY));kind=g.preyDeck.pop();t.hunt.kind=kind;}
    if(g.actions<1){p.pendingHunt=p.pos;g.combatTurnEnd={player:p.id};log(g,`${PREY[kind].name} 조우 · 행동이 없어 다음 자기 차례에 전투합니다.`);return;}
    const m=PREY[kind],lv=t.level-1,resume=t.hunt.resume||{};p.pendingHunt=null;
    g.battle={player:p.id,kind,level:t.level,hp:t.hunt.hp||m.hp[lv],maxHp:m.hp[lv],terrain:t.terrain,origin:p.pos,pattern:m.pattern.slice(),prepared:resume.prepared||0,armor:resume.armor||0,round:resume.round||1,stage:'plan',roundPaid:false,optional,plan:[],step:0,spent:[],order:null,partner:null,assist:null,allySpent:[],feed:[`${m.name}과 대치! 카드 3장을 계획해 전투 1회 · 행동 1을 사용합니다.`]};
    draw(g,p,4,true);log(g,`${m.name} Lv.${t.level} 조우 · 전투 한 라운드마다 1행동`,'danger');
  }
  function battleCardsBack(g){
    const b=g.battle,p=active(g);p.combatHand.push(...b.plan.slice(b.step));p.combatDiscard.push(...b.spent);
    const partner=b.partner!==null?g.players[b.partner]:null;
    for(const used of b.allySpent||[])g.players[used.player].combatDiscard.push(used.card);
    if(b.assist)g.players[b.assist.player].combatHand.push(b.assist.card);
    g.battle=null;draw(g,p,4,true);if(partner)draw(g,partner,4,true);return partner;
  }
  function pauseBattle(g){
    const b=g.battle,p=active(g),t=g.tiles[b.origin];
    t.hunt={kind:b.kind,hp:b.hp,resume:{round:b.round,armor:b.armor,prepared:b.prepared}};
    battleCardsBack(g);log(g,`${PREY[b.kind].name} 사냥 중단 · HP ${b.hp} 유지 · 현재 칸에서 다른 행동 가능`);
    if(g.actions===0)g.combatTurnEnd={player:p.id};
  }
  function finishBattle(g,win,fled=false){
    const b=g.battle,p=active(g),t=g.tiles[b.origin],partner=battleCardsBack(g);
    if(win){t.hunt=null;p.vp+=b.level;const loot=[...PREY[b.kind].loot,...(b.level===2?['metal']:[])];if(partner){const mine=[],theirs=[];loot.forEach((k,i)=>(i%2?theirs:mine).push(k));gain(g,p,mine);gain(g,partner,theirs);log(g,partner.name+'과 전리품을 번갈아 나눴습니다. 각자의 가방에 직접 배치하세요.','good');}else gain(g,p,loot);g.huntResult={player:p.id,kind:b.kind,level:b.level,points:b.level,loot:loot.map((kind,i)=>({kind,owner:partner&&i%2?partner.id:p.id}))};log(g,PREY[b.kind].name+' 사냥 성공 · +'+b.level+'점 · 전리품 획득','good');}
    else if(!fled){t.hunt.hp=b.hp;delete t.hunt.resume;rescue(g,p);endTurn(g,true);return;}
    if(g.actions===0)g.combatTurnEnd={player:p.id};
  }
  // Keep the acting player until all loot owners have finished receiving their pieces.
  function settleCombatTurn(g){
    if(g.ended||g.winner!==null)return;
    const busy=()=>g.battle||g.huntResult||g.pendingEvent||g.pendingDeparture||g.pendingExplore||g.tileSetup||g.gathering||g.payment||g.pending.length||g.loot.length;
    if(g.combatTurnEnd&&g.combatTurnEnd.player===active(g).id&&g.actions===0&&!busy())endTurn(g);
    const p=active(g);
    if(p.pendingHunt&&p.pendingHunt!==p.pos)p.pendingHunt=null;
    if(p.pendingHunt&&!busy()&&g.actions>0&&!g.ended&&g.winner===null){const tile=g.tiles[p.pendingHunt];p.pendingHunt=null;if(tile?.hunt)encounter(g,tile);}
  }
  function battleStep(g){const b=g.battle,p=active(g);assert(b?.stage==='resolve'&&b.player===p.id&&!g.ended&&g.winner===null,'먼저 행동 카드를 공개해주세요.');const c=b.plan[b.step],pc=COMBAT[c],effect={player:p.id,kind:b.kind,level:b.level,round:b.round,step:b.step+1,card:c,playerHp:p.hp,preyHp:b.hp,maxHp:b.maxHp,damage:0,playerDamage:0,preyAfter:b.hp,playerAfter:p.hp,reaction:null,killed:false,escaped:false};g.battleEffect=effect;b.spent.push(c);b.step++;
    const assist=b.assist;let power=pc.atk;const weapon=p.bag.find(i=>['spear','knife'].includes(i.kind)&&i.durability>0);if(pc.atk&&weapon){power++;weapon.durability--;if(!weapon.durability){p.bag=p.bag.filter(i=>i.id!==weapon.id);b.feed.unshift('무기가 파손되었습니다.');}}
    if(assist){power+=COMBAT[assist.card].atk;b.allySpent.push(assist);b.assist=null;b.feed.unshift(g.players[assist.player].name+'의 '+COMBAT[assist.card].name+' 지원');}
    let hit=Math.max(0,power-b.armor-(b.kind==='turtle'&&power>=3?1:0));b.armor=0;b.hp=Math.max(0,b.hp-hit);effect.damage=Math.min(hit,effect.preyHp);effect.preyAfter=b.hp;effect.power=power;effect.guard=pc.guard||0;b.feed.unshift(`${b.step}. ${pc.name} → 사냥감 피해 ${hit}${pc.guard?' · 방어 '+pc.guard:''}`);
    if(b.hp<=0){effect.killed=true;finishBattle(g,true);return;}
    if(b.kind==='deer'&&b.terrain==='plain'&&b.hp<=1){const options=Object.entries(routes(g,p.pos,2)).filter(([k,path])=>path.length&&g.tiles[k].terrain!=='plain'&&!g.tiles[k].safe&&!g.tiles[k].hunt).sort((a,z)=>z[1].length-a[1].length);if(options.length){const dest=options[0][0];g.tiles[dest].hunt={kind:'deer',hp:b.hp};g.tiles[b.origin].hunt=null;effect.escaped=true;effect.reaction={type:'flee',name:'긴급 도주',value:2};log(g,'노루의 도주! 다른 지형으로 이동했습니다.');finishBattle(g,false,true);return;}}
    const move=battleAction(b,b.step-1),label=`사냥감 ${move.letter} · ${move.name}`;effect.reaction={...move};
    if(move.type==='guard'){b.armor=move.value;b.feed.unshift(`${label} · 다음 공격 방어 ${b.armor}`);}
    else if(move.type==='prepare'){b.prepared=Math.max(b.prepared||0,move.value);b.feed.unshift(`${label} · 다음 공격 +${b.prepared} (중복되지 않음)`);}
    else if(move.type==='flee'){const dest=neighbors(b.origin).find(k=>g.tiles[k]&&!g.tiles[k].safe&&g.tiles[k].terrain!==b.terrain&&!g.tiles[k].hunt);if(dest){g.tiles[dest].hunt={kind:b.kind,hp:b.hp};g.tiles[b.origin].hunt=null;effect.escaped=true;log(g,`${PREY[b.kind].name}의 도주! 다른 지형으로 1칸 이동했습니다. HP ${b.hp} 유지 · 전리품 없음`);finishBattle(g,false,true);return;}b.feed.unshift(`${label} · 이동할 다른 지형이 없어 대기`);}
    else if(move.type==='attack'){const prepared=b.prepared||0;let atk=move.value+prepared+(b.kind==='boar'&&b.hp<=b.maxHp/2?1:0);b.prepared=0;const damage=Math.max(0,atk-pc.guard-(assist?COMBAT[assist.card].guard:0));p.hp=Math.max(0,p.hp-damage);effect.playerDamage=Math.min(damage,effect.playerHp);effect.playerAfter=p.hp;effect.monsterPower=atk;b.feed.unshift(`${label} · 공격 ${atk}${prepared?' (준비 +'+prepared+')':''} → 내 피해 ${damage}`);if(p.hp<=0){finishBattle(g,false);return;}}
    if(b.step===3){b.round++;b.stage='choice';b.roundPaid=false;b.step=0;b.plan=[];b.order=null;draw(g,p,4,true);b.feed.unshift(`라운드 ${b.round-1} 완료 · 남은 행동 ${g.actions}회`);if(g.actions===0)pauseBattle(g);}
  }
  function board(p,id){return [...p.storage,...p.boards].find(b=>b.id===id);}
  function pieceCells(piece){return shape(piece.shape,piece.rotation||0,piece.flip||false);}
  function canPlace(p,piece,id,x,y,source){const b=board(p,id);if(!b||b.complete||(!pieceRecipe(piece?.material,piece?.shape)&&!retiredPiece(piece))||!!piece.flip&&!retiredPiece(piece)||!Number.isInteger(x)||!Number.isInteger(y)||b.requires&&!p.boards.find(z=>z.id===b.requires)?.complete)return false;const cells=pieceCells(piece),mask=boardMask(b);if(cells.some(([a,c])=>x+a<0||x+a>=b.w||y+c<0||y+c>=b.h||!mask[(y+c)*b.w+x+a]||(b.cells[(y+c)*b.w+x+a]&&b.cells[(y+c)*b.w+x+a].id!==source)))return false;if(b.needs){const amount=b.cells.filter(c=>c?.material===piece.material&&c.id!==source).length;if(amount+cells.length>(b.needs[piece.material]||0))return false;}for(const zone of b.zones||[]){const added=cells.filter(([a,c])=>zone.indices.includes((y+c)*b.w+x+a)).length,amount=zone.indices.filter(i=>b.cells[i]?.material===piece.material&&b.cells[i]?.id!==source).length;if(amount+added>(zone.needs[piece.material]||0))return false;}return true;}
  function place(g,a){const p=active(g);assert(p.pos==='0,0','캠프에서만 자재를 배치할 수 있습니다.');let piece,src;if(a.source==='pending'){piece=g.pending[0];assert(piece,'배치할 조각이 없습니다.');}else{src=p.storage.find(s=>s.cells.some(c=>c?.id===a.source));assert(src,'보관된 조각을 선택해주세요.');piece=src.cells.find(c=>c?.id===a.source);}
    assert(!a.flip||retiredPiece(piece),'건설 조각은 회전만 가능합니다. 뒤집을 수 없습니다.');piece={...piece,rotation:a.rotation||0,flip:!!a.flip};assert(canPlace(p,piece,a.board,a.x,a.y,piece.id),'이 위치에는 놓을 수 없습니다. 모양·빈칸·재료 조건을 확인해주세요.');if(src)src.cells=src.cells.map(c=>c?.id===piece.id?null:c);else g.pending.shift();const b=board(p,a.board);for(const [x,y]of pieceCells(piece))b.cells[(a.y+y)*b.w+a.x+x]={...piece,x:a.x,y:a.y};claimBoardBonuses(g,p,b,piece);if(b.zones?.length){completeBoardLevels(g,p,b);return;}if(b.needs&&boardMask(b).every((used,i)=>!used||b.cells[i])){b.complete=true;p.vp+=b.vp;if(b.effect==='pack'){p.bagUnlocks=bagUnlocked(p).slice();const next=BAG.groups.find(group=>!p.bagUnlocks.includes(group));if(next)p.bagUnlocks.push(next);p.capacity=12+p.bagUnlocks.length*3;}if(b.effect==='warehouse')p.storage.push({id:'extra',name:'확장 보관소',w:4,h:4,cells:Array(16).fill(null)});log(g,`${p.name} · ${b.name} 완성! +${b.vp}점`,'good');}}
  function enterTile(g,p,to,running=false,label=''){
    if(p.pos==='0,0'&&to!=='0,0'){
      assert(!g.pendingDeparture,'출발 보급을 먼저 정리해주세요.');const item=makeItem(g,'berry',{owner:p.id,origin:'0,0',source:'camp-departure'});g.loot.push(item);g.pendingDeparture={player:p.id,from:'0,0',to,running,label,lootId:item.id};log(g,`${p.name} · 출발 보급 산딸기 1개를 가방에 넣거나 캠프에 두면 이동합니다.`,'good');return;
    }
    arriveTile(g,p,to,running,label);
  }
  function finishDeparture(g){
    const d=g.pendingDeparture;if(!d)return;const p=active(g);assert(d.player===p.id&&d.from==='0,0'&&p.pos===d.from&&d.to!==d.from&&typeof d.running==='boolean'&&typeof d.lootId==='string'&&routes(g,d.from,d.running?2:1)[d.to]?.length,'저장된 출발 위치와 목적지를 확인해주세요.');assert(!g.ended&&g.winner===null&&!g.pendingEvent&&!g.pendingExplore&&!g.tileSetup&&!g.battle&&!g.gathering&&!g.payment&&!g.pending.length,'출발 보급과 다른 진행 중인 행동이 겹칩니다.');assert(capacityOK(g,d.to,p),'그 타일에는 이미 탐험가 2명이 있습니다.');const waiting=g.loot.find(i=>i.id===d.lootId);if(waiting){assert(waiting.owner===p.id&&waiting.kind==='berry'&&waiting.origin===d.from&&waiting.source==='camp-departure','출발 보급 정보를 확인해주세요.');return;}
    const delivered=p.bag.concat(groundItems(g,d.from)).find(i=>i.id===d.lootId);assert(delivered&&delivered.kind==='berry'&&delivered.source==='camp-departure','출발 보급의 수령 또는 캠프 보관 기록이 없습니다.');g.pendingDeparture=null;arriveTile(g,p,d.to,d.running,d.label||'');
  }
  function arriveTile(g,p,to,running=false,label=''){p.pos=to;if(to==='0,0'){p.hp=8;p.hunger=6;p.detection=0;log(g,`${p.name} → 베이스캠프 · HP 8 / 포만감 6 / 발각 0 · 턴 종료`,'good');endTurn(g);return;}if(running)detect(g,1,p);else checkDetection(g,p);log(g,`${p.name} → ${TERRAIN[g.tiles[to].terrain].name}${running?' · 달리기':label?' · '+label:''}`);quests(g,p);event(g,g.tiles[to]);if(!g.pendingEvent)encounter(g,g.tiles[to]);}
  function endTurn(g,forced=false){validTurn(g,forced);const p=active(g);g.combatTurnEnd=null;quests(g,p);if(p.pos!=='0,0'){p.hunger=Math.max(0,p.hunger-1);log(g,`${p.name} 턴 종료 · 포만감 −1 (${p.hunger}/6)`);if(!p.hunger){p.discard.push('hunger');log(g,`${p.name} 포만감 0 · 허기 카드가 버린더미에 추가됩니다.`,'danger');}}draw(g,p);g.turn=(g.turn+1)%g.players.length;if(!g.turn){dinosaurTurn(g);g.round++;if(g.round>30){g.ended=true;log(g,'30라운드 종료. 비행기로 출발하지 못해 원정이 끝났습니다.','danger');}}g.actions=2;log(g,`${active(g).name}의 턴 · 2행동`);}
  const PAID_TYPES=['process','cook','combineFood','craft','heal','aircraftCraft','submitQuest'];
  function checkCards(g,indices,normal=false){const p=active(g);assert(Array.isArray(indices)&&indices.length&&new Set(indices).size===indices.length,'사용할 손패를 선택해주세요.');assert(indices.every(i=>Number.isInteger(i)&&i>=0&&i<p.hand.length),'선택한 카드가 손패에 없습니다.');if(normal)assert(indices.every(i=>CARDS[p.hand[i]]&&p.hand[i]!=='hunger'),'허기와 퀘스트 카드는 가공에 사용할 수 없습니다.');}
  function paymentPlan(g,type,data={}){
    const p=active(g);assert(type!=='escape','개인 탈출은 공용 비행기 출발로 대체되었습니다.');assert(PAID_TYPES.includes(type),'지원하지 않는 지불 행동입니다.');let cost={},cards=type==='process'?data.cards:type==='cook'&&Array.isArray(data.cards)?data.cards:[data.card],actions=1,requiredIds=[],results=[];
    if(type==='process'){
      assert(p.pos==='0,0','가공은 베이스캠프에서 할 수 있습니다.');assert(Array.isArray(data.cards)&&data.cards.length>=1&&data.cards.length<=2&&Array.isArray(data.recipes)&&data.recipes.length===data.cards.length,'카드 1~2장과 같은 수의 가공식을 선택해주세요.');
      const needed={};for(const r of data.recipes){const recipe=pieceRecipe(r.material,r.shape),m=MATERIALS[r.material];assert(recipe?.craftable&&m?.shapes.includes(r.shape),'가공할 수 있는 재료와 모양을 선택해주세요.');cost[m.raw]=(cost[m.raw]||0)+recipe.cost;const stockKey=`${r.material}:${r.shape}`;needed[stockKey]=(needed[stockKey]||0)+1;assert(pieceStock(g,r.material,r.shape)>=needed[stockKey],'해당 모양의 공용 자재 조각이 부족합니다.');}
    }else if(type==='cook'){
      assert(data.tea!==true,'허브 조합은 조리 목록에서 선택해주세요.');
      const max=p.pos==='0,0'?(p.boards.find(b=>b.id==='kitchen')?.complete?3:2):1;
      assert(Array.isArray(data.items)&&data.items.length>0&&data.items.length<=max&&new Set(data.items).size===data.items.length,'조리할 식재료를 선택해주세요. 탐험 중에는 한 개씩 조리합니다.');
      assert(cards.length===data.items.length,'완성 음식 한 개마다 손패 한 장이 필요합니다.');
      const items=data.items.map(id=>p.bag.find(i=>i.id===id));assert(items.every(i=>i&&!i.topping&&['fish','meat','mushroom'].includes(i.kind)),'조리할 식재료가 가방에 없습니다.');
      cost={branch:1};for(const item of items)cost[item.kind]=(cost[item.kind]||0)+1;requiredIds=data.items.slice();results=items.map(i=>({fish:'cookedFish',meat:'cookedMeat',mushroom:'cookedMushroom'}[i.kind]));
    }else if(type==='combineFood'){
      const {base,herb}=foodParts(p,data);cost={[base.kind]:1,[herb.kind]:1};requiredIds=[base.id,herb.id];
    }else if(type==='craft'){
      assert(!p.bag.some(i=>i.kind==='spear'),'이미 돌창을 가지고 있습니다.');cost={branch:1,stone:1,stem:1};results=['spear'];
    }else if(type==='heal'){
      assert(p.hp<8,'체력이 이미 가득합니다.');cost={herb:1};
    }else if(type==='aircraftCraft'){
      assert(p.pos==='0,0','비행기 부품은 베이스캠프의 기본 작업대에서 제작합니다.');const recipe=AIRCRAFT_RECIPES[data.recipe];assert(recipe,'제작할 비행기 부품을 선택해주세요.');cost={...recipe.cost};results=recipe.results.slice();if(data.steelShape!==undefined){assert(data.recipe==='steel'&&AIRCRAFT_STEEL_SHAPES.includes(data.steelShape),'강철 조각의 모양을 선택해주세요.');results=['steel'];}
    }else if(type==='submitQuest'){
      assert(p.pos==='0,0','채집 메모의 재료는 베이스캠프에서 반납합니다.');assert(p.quests.some(q=>q.id===(data.quest??data.id)&&q.type==='supply'&&!q.done),'반납할 채집 퀘스트가 없습니다.');cost={branch:1,stone:1,stem:1};cards=[];actions=0;
    }
    assert(g.actions>=actions,'남은 행동이 없습니다.');if(cards.length)checkCards(g,cards,type==='process'||type==='aircraftCraft');assert(hasCost(p,cost),'필요한 재료가 부족합니다.');return {cost,cards:cards.slice(),actions,requiredIds,results};
  }
  function beginPayment(g,type,data){validTurn(g);assert(!g.payment,'진행 중인 지불을 먼저 마쳐주세요.');const plan=paymentPlan(g,type,data);g.payment={player:active(g).id,type,data:clone(data),cost:plan.cost,offered:[],requiredIds:plan.requiredIds,cards:plan.cards,actions:plan.actions};}
  function paymentItems(g){const p=active(g),tray=g.payment;assert(tray&&tray.player===p.id,'진행 중인 지불이 없습니다.');return {p,tray,items:tray.offered.map(id=>p.bag.find(i=>i.id===id))};}
  function offerPayment(g,id){const {p,tray,items}=paymentItems(g),item=p.bag.find(i=>i.id===id);assert(item&&!tray.offered.includes(id),'가방에서 아직 올리지 않은 물건을 선택해주세요.');assert(!item.topping,'조합된 음식은 먼저 분리한 뒤 재료로 지불해주세요.');assert(tray.cost[item.kind]&&items.filter(i=>i?.kind===item.kind).length<tray.cost[item.kind],'이 종류는 더 지불할 필요가 없습니다.');if(tray.type==='combineFood'||tray.type==='cook'&&!tray.data.tea&&item.kind!=='branch')assert(tray.requiredIds.includes(id),'조리 대상으로 선택한 식재료를 올려주세요.');tray.offered.push(id);}
  function commitPayment(g){
    const {p,tray,items}=paymentItems(g),plan=paymentPlan(g,tray.type,tray.data);assert(new Set(tray.offered).size===tray.offered.length&&items.every(i=>i&&!i.topping),'지불할 물건을 다시 확인해주세요.');
    assert(items.length===Object.values(plan.cost).reduce((n,v)=>n+v,0)&&Object.entries(plan.cost).every(([kind,n])=>items.filter(i=>i.kind===kind).length===n)&&plan.requiredIds.every(id=>tray.offered.includes(id)),'필요한 재료를 모두 지불 칸에 올려주세요.');
    if(plan.cards.length)spend(g,plan.cards,plan.actions,tray.type==='process');const paid=new Set(tray.offered),keep=['cook','combineFood'].includes(tray.type)?new Set(plan.requiredIds):new Set;p.bag=p.bag.filter(i=>!paid.has(i.id)||keep.has(i.id));g.payment=null;
    if(tray.type==='process'){g.pending=tray.data.recipes.map(r=>takePiece(g,r.material,r.shape));log(g,`${g.pending.length}개 자재 가공 · 지금 모두 배치해야 합니다.`);}
    if(tray.type==='cook'){plan.requiredIds.forEach((id,i)=>p.bag.find(item=>item.id===id).kind=plan.results[i]);log(g,'식재료를 가방의 원래 자리에서 구운 면으로 뒤집었습니다.','good');}
    if(tray.type==='combineFood')applyFoodCombination(g,tray.data);
    if(tray.type==='craft'){gain(g,p,plan.results,{source:'crafted'});log(g,'돌창 조합 · 공격 +1 / 내구도 6 / 가방 3칸','good');}
    if(tray.type==='heal'){p.hp=Math.min(8,p.hp+3);log(g,'허브 치료 · 체력 +3','good');}
    if(tray.type==='aircraftCraft'){gain(g,p,plan.results,{source:'crafted',...(tray.data.steelShape?{steelShape:tray.data.steelShape}:{})});log(g,`${AIRCRAFT_RECIPES[tray.data.recipe].name} 제작 · 완성품은 임시 공간에서 가방으로 무료로 옮기세요.`,'good');}
    if(tray.type==='submitQuest'){const q=p.quests.find(q=>q.id===(tray.data.quest??tray.data.id));p.discard.push('harvest');completeQuest(g,p,q);}
  }
  function startGather(g,cardIndex){validTurn(g);const p=active(g),cardType=p.hand[cardIndex],all=cardType==='harvest';assert(all||cardType==='gather','채집 또는 집중채집 카드를 선택해주세요.');checkCards(g,[cardIndex]);assert(g.actions>=1,'남은 행동이 없습니다.');assert(tileResourceCount(g.tiles[p.pos]),'이 타일의 자원이 소진되었습니다.');g.gathering={player:p.id,tile:p.pos,card:cardIndex,cardType,all,limit:all?tileResourceCount(g.tiles[p.pos]):3,taken:0,paid:false};}
  function gatherTake(g,a,discard=false){
    const p=active(g),s=g.gathering;assert(s&&s.player===p.id&&s.tile===p.pos,'진행 중인 채집이 없습니다.');assert(a.tile===undefined||a.tile===s.tile,'현재 채집 중인 지형의 물건만 가져올 수 있습니다.');const t=g.tiles[s.tile],fromGround=a.groundId!==undefined,at=fromGround?groundItems(g,s.tile).findIndex(i=>i.id===a.groundId):a.index;assert(Number.isInteger(at)&&at>=0&&at<(fromGround?groundItems(g,s.tile).length:t.resources.length),'타일에 남아 있는 자원 토큰을 골라주세요.');assert(s.taken<s.limit,'이번 채집 수량을 모두 가져왔습니다.');const original=fromGround?t.groundItems[at]:null,kind=original?.kind||t.resources[at];assert(!a.kind||a.kind===kind,'타일 자원이 바뀌었습니다. 토큰을 다시 잡아주세요.');
    if(discard){assert(canFinishGather(g),'집중채집 중 담을 수 있는 자원이 남아 있습니다. 가방에 놓거나 공간이 없을 때 마쳐주세요.');g.gathering=null;log(g,'남은 자원을 지형에 그대로 두고 채집을 마쳤습니다.');return;}
    const item=original?{...original,x:a.x,y:a.y,rotation:a.rotation??original.rotation??0,flip:a.flip??original.flip??false}:makeItem(g,kind,{origin:s.tile,x:a.x,y:a.y,rotation:a.rotation??0,flip:!!a.flip});delete item.owner;assert(bagFits(p,item,a.x,a.y),'가방의 빈칸에 모양을 맞춰 놓아주세요. 물건은 지형에 그대로 남아 있습니다.');
    if(!s.paid){const cardIndex=p.hand[s.card]===s.cardType?s.card:p.hand.indexOf(s.cardType);card(g,cardIndex,s.cardType);spend(g,[cardIndex]);detect(g,s.all?2:1,p);s.paid=true;}
    if(fromGround)t.groundItems.splice(at,1);else t.resources.splice(at,1);p.bag.push(item);s.taken++;log(g,`${itemName(item)} 채집 · 가방 배치 (${s.taken}/${s.limit})`);if(s.taken>=s.limit||!tileResourceCount(t)||!canGatherFit(g))g.gathering=null;
  }
  function autoGather(g){
    const p=active(g),session=g.gathering;assert(session&&session.player===p.id&&session.tile===p.pos,'진행 중인 채집이 없습니다.');
    while(g.gathering){const t=g.tiles[session.tile],choices=[...(t.resources||[]).map((kind,index)=>({item:{kind},index})),...groundItems(g,session.tile).map(item=>({item,groundId:item.id}))];let selected;
      for(const choice of choices){const fit=findBagSpace(p,choice.item,true);if(fit){selected={...choice,fit};break;}}
      if(!selected){g.gathering=null;log(g,'담을 수 있는 빈 가방 칸이 없어 남은 자원을 지형에 두고 채집을 마쳤습니다.');break;}
      const {fit,index,groundId}=selected;gatherTake(g,{index,groundId,x:fit.x,y:fit.y,rotation:fit.rotation,flip:fit.flip});
    }
  }
  function completeQuest(g,p,q){q.done=true;for(const area of ['hand','deck','discard'])p[area]=p[area].filter(c=>c!==`quest:${q.id}`);p.vp+=2;log(g,`${p.name} · ${q.name} 완료! +2점`,'good');}
  const AIRCRAFT_POINTS={steel:1,engine:6,cooler:4,battery:5};
  const LEGACY_AIRCRAFT_ZONES=[
    {id:'engine',name:'엔진부',w:3,h:3,slots:['engine','engine','steel','engine','engine','steel','steel','steel','steel']},
    {id:'wingLeft',name:'왼쪽 날개',w:4,h:2,slots:Array(8).fill('steel')},
    {id:'wingRight',name:'오른쪽 날개',w:4,h:2,slots:Array(8).fill('steel')},
    {id:'cooling',name:'냉각부',w:3,h:2,slots:['cooler','cooler','steel','steel','steel','steel']},
    {id:'power',name:'전력부',w:2,h:2,slots:['battery','steel','battery','battery']}
  ];
  const AIRCRAFT_ZONES=[{"id": "engine", "name": "엔진부", "x": 5, "y": 0, "w": 4, "h": 4, "slots": ["engine", "engine", null, null, "engine", "engine", "steel", "steel", null, "steel", "steel", null, "steel", "steel", "steel", "steel"]}, {"id": "wingLeft", "name": "왼쪽 날개", "x": 0, "y": 3, "w": 5, "h": 4, "slots": [null, null, null, null, "steel", null, "steel", "steel", "steel", "steel", "steel", "steel", "steel", "steel", "steel", null, "steel", "steel", "steel", "steel"]}, {"id": "wingRight", "name": "오른쪽 날개", "x": 9, "y": 3, "w": 5, "h": 4, "slots": ["steel", "steel", null, null, null, "steel", "steel", "steel", "steel", null, "steel", "steel", "steel", "steel", "steel", null, "steel", "steel", null, null]}, {"id": "power", "name": "전력부", "x": 5, "y": 4, "w": 4, "h": 3, "slots": ["battery", "steel", "battery", "steel", "battery", "battery", "battery", "battery", "steel", "steel", "steel", "steel"]}, {"id": "cooling", "name": "냉각부", "x": 5, "y": 7, "w": 4, "h": 3, "slots": ["cooler", "cooler", "steel", "steel", "steel", "steel", "steel", null, null, "steel", "steel", null]}];
  const AIRCRAFT_RECIPES={
    steel:{name:'강철판',cost:{metal:1,branch:1},results:['steel','steel','steel','steel'],shape:[[0,0]],cells:1,points:1},
    engine:{name:'비행기 엔진',cost:{metal:2,stone:1,stem:1},results:['engine'],shape:[[0,0],[1,0],[0,1],[1,1]],cells:4,points:6},
    cooler:{name:'냉각장치',cost:{metal:1,water:1,stem:1},results:['cooler'],shape:[[0,0],[1,0]],cells:2,points:4}
  };
  const AIRCRAFT_STEEL_SHAPES=['I','O','T','L','S'];
  const aircraftPoints=item=>item.kind==='steel'?itemCells(item).length:AIRCRAFT_POINTS[item.kind];
  function aircraftCells(){return AIRCRAFT_ZONES.flatMap(z=>z.slots.flatMap((kind,index)=>kind?[{zone:z.id,index,x:z.x+index%z.w,y:z.y+Math.floor(index/z.w),kind}]:[]));}
  function createAircraft(players=[]){return {layoutVersion:2,zones:Object.fromEntries(AIRCRAFT_ZONES.map(z=>[z.id,{cells:Array(z.w*z.h).fill(null)}])),contributions:Object.fromEntries(players.map(p=>[p.id,0])),ready:false,departed:false,scores:[]};}
  function aircraftProgress(g){if(g.aircraft?.departed&&g.aircraft.legacyCompletedCells)return {filled:g.aircraft.legacyCompletedCells,total:g.aircraft.legacyCompletedCells,ready:true};const layout=aircraftCells(),filled=layout.filter(c=>g.aircraft?.zones?.[c.zone]?.cells[c.index]?.kind===c.kind).length;return {filled,total:layout.length,ready:filled===layout.length};}
  function validateAircraftInstall(g,a){
    validTurn(g);assert(!g.pendingDeparture&&!g.pendingEvent&&!g.pendingExplore&&!g.tileSetup&&!g.gathering&&!g.payment,'진행 중인 자원 배치나 행동을 먼저 마쳐주세요.');const p=active(g),plane=g.aircraft;assert(p?.pos==='0,0','비행기 부품은 베이스캠프에서 설치합니다.');assert(plane&&!plane.departed,'조립할 공용 비행기가 없습니다.');
    const item=p.bag.find(i=>i.id===a.id);assert(item&&Object.prototype.hasOwnProperty.call(AIRCRAFT_POINTS,item.kind),'자신의 가방에서 비행기 부품을 선택해주세요.');assert(!Object.values(plane.zones).some(z=>z.cells.some(c=>c?.id===item.id)),'이미 설치한 부품입니다.');
    const zone=AIRCRAFT_ZONES.find(z=>z.id===a.zone);assert(zone||a.zone==='grid','비행기의 설치 구역을 선택해주세요.');assert(Number.isInteger(a.x)&&Number.isInteger(a.y),'정확한 설치 칸을 선택해주세요.');const rotation=a.rotation??item.rotation??0,flip=a.flip??item.flip??false;assert(Number.isInteger(rotation)&&typeof flip==='boolean','부품의 회전과 뒤집기 값을 확인해주세요.');
    const x=a.x+(zone?.x||0),y=a.y+(zone?.y||0),layout=aircraftCells();
    const targets=itemCells({...item,rotation,flip}).map(([dx,dy])=>layout.find(c=>c.x===x+dx&&c.y===y+dy));
    assert(targets.every(Boolean),'부품이 연결된 도면 밖으로 나갑니다.');assert(targets.every(c=>c.kind===item.kind&&!plane.zones[c.zone].cells[c.index]),'비어 있는 같은 종류의 부품 칸에 맞춰 놓아주세요.');return {p,plane,item,targets};
  }
  function canInstallAircraft(g,a={}){try{validateAircraftInstall(g,a);return true;}catch{return false;}}
  function installAircraft(g,a){const {p,plane,item,targets}=validateAircraftInstall(g,a);p.bag=p.bag.filter(i=>i.id!==item.id);for(const c of targets)plane.zones[c.zone].cells[c.index]={id:item.id,kind:item.kind,owner:p.id,...(item.steelShape?{steelShape:item.steelShape}:{})};const points=aircraftPoints(item);plane.contributions[p.id]=(plane.contributions[p.id]||0)+points;plane.ready=aircraftProgress(g).ready;log(g,`${p.name} · ${RES[item.kind].name} 설치 · 공헌 +${points}${plane.ready?' · 공용 비행기 조립 완료!':''}`,'good');}
  function departAircraft(g){
    validTurn(g);assert(!g.pendingDeparture&&!g.pendingEvent&&!g.pendingExplore&&!g.tileSetup&&!g.gathering&&!g.payment,'진행 중인 자원 배치나 행동을 먼저 마쳐주세요.');const p=active(g),plane=g.aircraft;assert(p?.pos==='0,0','베이스캠프에서 비행기를 출발시킵니다.');assert(plane&&!plane.departed&&aircraftProgress(g).ready,'비행기의 모든 부품을 먼저 설치해주세요.');assert(g.players.every(p=>p.pos==='0,0'),'모든 탐험가가 베이스캠프로 돌아와야 출발할 수 있습니다.');
    const scores=g.players.map(p=>({player:p.id,name:p.name,base:p.vp,contribution:plane.contributions[p.id]||0,total:p.vp+(plane.contributions[p.id]||0)})).sort((a,b)=>b.total-a.total||a.player-b.player);scores.forEach((s,i)=>s.rank=i&&scores[i-1].total===s.total?scores[i-1].rank:i+1);for(const s of scores)g.players.find(p=>p.id===s.player).vp=s.total;
    plane.ready=true;plane.departed=true;plane.departedRound=g.round;plane.scores=scores;g.winners=scores.filter(s=>s.total===scores[0].total).map(s=>s.player);g.winner=g.winners[0];g.ended=true;log(g,`전원 비행기로 출발! ${scores.filter(s=>s.rank===1).map(s=>s.name).join(' · ')} ${g.winners.length>1?'공동 ':''}우승 · ${scores[0].total}점`,'good');
  }
  function restoreAircraft(g){
    if(!g.aircraft){g.aircraft=createAircraft(g.players);if(g.winner!==null||g.ended)g.aircraft.legacyResult=true;return;}
    const plane=g.aircraft;plane.zones=plane.zones||{};
    if(!plane.layoutVersion){
      const oldParts=new Map();
      for(const z of LEGACY_AIRCRAFT_ZONES){const cells=plane.zones[z.id]?.cells||Array(z.slots.length).fill(null);assert(cells.length===z.slots.length,'이전 비행기 도면의 크기가 맞지 않습니다.');cells.forEach((c,i)=>{if(!c)return;assert(c.kind===z.slots[i],'이전 비행기 부품의 위치를 확인해주세요.');let part=oldParts.get(c.id);if(!part){part={...c,zone:z.id,cells:[]};oldParts.set(c.id,part);}assert(part.zone===z.id&&part.kind===c.kind&&part.owner===c.owner,'이전 비행기 부품이 중복되어 있습니다.');part.cells.push([i%z.w,Math.floor(i/z.w)]);});}
      const zones=createAircraft(g.players).zones;
      for(const part of oldParts.values()){
        const normalized=transformCells(part.cells).map(c=>c.join(',')).sort().join('|');assert([0,1,2,3].some(r=>[false,true].some(f=>itemCells({...part,rotation:r,flip:f}).map(c=>c.join(',')).sort().join('|')===normalized)),'이전 비행기 부품의 모양을 확인해주세요.');
        const z=AIRCRAFT_ZONES.find(z=>z.id===part.zone);let target;
        for(let y=0;y<z.h&&!target;y++)for(let x=0;x<z.w&&!target;x++)for(let r=0;r<4&&!target;r++)for(const f of [false,true]){const cells=itemCells({...part,rotation:r,flip:f}).map(([dx,dy])=>({x:x+dx,y:y+dy}));if(cells.every(c=>c.x<z.w&&c.y<z.h&&z.slots[c.y*z.w+c.x]===part.kind&&!zones[z.id].cells[c.y*z.w+c.x])){target=cells.map(c=>c.y*z.w+c.x);break;}}
        assert(target,'이전 비행기 부품을 새 도면으로 옮기지 못했습니다.');for(const index of target)zones[z.id].cells[index]={id:part.id,kind:part.kind,owner:part.owner};
      }
      plane.zones=zones;plane.layoutVersion=2;if(plane.departed)plane.legacyCompletedCells=35;log(g,'비행기 도면을 연결된 60칸으로 확장했습니다. 기존 납품 부품과 공헌도를 보존했습니다.');
    }
    assert(plane.layoutVersion===2,'지원하지 않는 비행기 도면입니다.');const items=new Map();
    for(const z of AIRCRAFT_ZONES){const cells=plane.zones[z.id]?.cells;assert(Array.isArray(cells)&&cells.length===z.slots.length,'저장된 비행기 구역의 크기가 맞지 않습니다.');cells.forEach((c,i)=>{if(!c)return;assert(typeof c.id==='string'&&c.id&&c.kind===z.slots[i]&&g.players.some(p=>p.id===c.owner),'저장된 비행기 부품 정보를 확인해주세요.');let item=items.get(c.id);if(!item){item={kind:c.kind,owner:c.owner,steelShape:c.steelShape,cells:[]};items.set(c.id,item);}assert(item.kind===c.kind&&item.owner===c.owner&&item.steelShape===c.steelShape,'저장된 비행기 부품이 중복되어 있습니다.');item.cells.push([z.x+i%z.w,z.y+Math.floor(i/z.w)]);});}
    const contributions=Object.fromEntries(g.players.map(p=>[p.id,0]));for(const [id,item] of items){const normalized=transformCells(item.cells).map(c=>c.join(',')).sort().join('|');let legal=false;for(let r=0;r<4;r++)for(const flip of [false,true])if(itemCells({...item,rotation:r,flip}).map(c=>c.join(',')).sort().join('|')===normalized)legal=true;assert(legal,'저장된 비행기 부품의 모양이 맞지 않습니다.');assert(!g.players.some(p=>p.bag.flatMap(itemParts).some(i=>i.id===id))&&!g.loot.concat(allGroundItems(g)).flatMap(itemParts).some(i=>i.id===id),'설치된 비행기 부품이 가방에 중복되어 있습니다.');contributions[item.owner]+=aircraftPoints(item);}
    plane.contributions=contributions;plane.ready=aircraftProgress(g).ready;plane.departed=!!plane.departed;plane.scores=plane.scores||[];
  }
  const FOOD_STACKS=[
    {base:'berry',topping:'herb',name:'허브 산딸기'},
    {base:'water',topping:'herb',name:'허브물'},
    {base:'cookedFish',topping:'herb',name:'허브 생선구이'},
    {base:'cookedMeat',topping:'herb',name:'허브 고기구이'},
    {base:'cookedMushroom',topping:'herb',name:'허브 버섯구이'}
  ].map(r=>({...r,id:`${r.base}-herb`,bonus:1,maxLayers:2,food:(RES[r.base].food||0)+1}));
  function foodValue(item){if(!item)return 0;const value=RES[item.kind]?.food||0;if(!item.topping)return value;const recipe=FOOD_STACKS.find(r=>r.base===item.kind&&r.topping===item.topping.kind);return recipe&&!item.topping.topping?value+(RES[item.topping.kind]?.food||0)+recipe.bonus:0;}
  function itemName(item){if(!item)return '';const recipe=item.topping&&FOOD_STACKS.find(r=>r.base===item.kind&&r.topping===item.topping.kind);return recipe?.name||RES[item.kind]?.name||item.kind;}
  function itemParts(item){return [item,...(item.topping?itemParts(item.topping):[])];}
  const materialCount=(p,kind)=>p.bag.flatMap(itemParts).filter(i=>i.kind===kind).length;
  function validateFoodAction(g){validTurn(g);assert(!g.pendingDeparture&&!g.pendingEvent&&!g.pendingExplore&&!g.tileSetup&&!g.gathering&&!g.payment,'진행 중인 자원 배치나 행동을 먼저 마쳐주세요.');}
  function foodParts(p,a){const source=p.bag.find(i=>i.id===a.source),target=p.bag.find(i=>i.id===a.target);assert(source&&target&&source.id!==target.id,'자기 가방의 서로 다른 음식 두 개를 선택해주세요.');assert(!source.topping&&!target.topping&&itemCells(source).length===1&&itemCells(target).length===1,'음식은 한 칸짜리 재료 두 개까지만 쌓을 수 있습니다.');const base=source.kind==='herb'?target:source,herb=source.kind==='herb'?source:target;assert(FOOD_STACKS.some(r=>r.base===base.kind&&r.topping===herb.kind),'허브를 산딸기·물·구운 음식과 조합해주세요.');return {p,base,herb,target};}
  function stackFoodParts(g,a){validateFoodAction(g);return foodParts(active(g),a);}
  function canStackFood(g,a={}){try{stackFoodParts(g,a);return true;}catch{return false;}}
  function applyFoodCombination(g,a){const {p,base,herb,target}=foodParts(active(g),a),combined={...base,x:target.x,y:target.y,topping:{...herb}};p.bag=p.bag.filter(i=>i.id!==base.id&&i.id!==herb.id);p.bag.push(combined);log(g,`${itemName(combined)} 조합 · 2층 / 가방 1칸 / 포만감 +${foodValue(combined)}`,'good');}
  function stackFood(g,a){validateFoodAction(g);beginPayment(g,'combineFood',a);}
  function splitFood(g,a){validateFoodAction(g);const p=active(g),base=p.bag.find(i=>i.id===a.id);assert(base?.topping,'분리할 2층 음식을 선택해주세요.');const top={...base.topping,x:a.x,y:a.y};assert(bagFits(p,top,a.x,a.y),'허브를 꺼내 놓을 빈 가방 칸이 필요합니다.');delete base.topping;p.bag.push(top);log(g,'음식을 두 재료로 분리했습니다.');}
  function validateSavedFood(g){const items=g.players.flatMap(p=>p.bag).concat(g.loot,allGroundItems(g));for(const i of items)if(i.topping){assert(typeof i.topping.id==='string'&&i.topping.id&&i.topping.id!==i.id&&!i.topping.topping&&FOOD_STACKS.some(r=>r.base===i.kind&&r.topping===i.topping.kind),'저장된 음식 조합의 재료나 층수를 확인해주세요.');}const ids=items.flatMap(itemParts).map(i=>i.id);assert(new Set(ids).size===ids.length,'가방·지급 대기·현장에 같은 물건이 중복되어 있습니다.');}
  function actMutable(g,type,a={},context={}){const p=active(g);if(type==='confirmHuntResult'){assert(g.huntResult&&g.huntResult.player===p.id,'확인할 사냥 결과가 없습니다.');g.huntResult=null;return g;}assert(!g.huntResult,'사냥 성공과 전리품을 먼저 확인해주세요.');assert(!g.pendingDeparture||['placeLoot','autoCollectLoot','discardLoot','bagMove','discardItem','eat'].includes(type),'출발 보급 산딸기를 가방에 넣거나 캠프에 두면 이동합니다.');assert(!g.pendingEvent||['drawEvent','resolveEvent'].includes(type),'이벤트 카드를 뒤집고 내용을 먼저 확인해주세요.');if(type==='drawEvent'){drawEvent(g);return g;}if(type==='resolveEvent'){resolveEvent(g);return g;}assert(!g.tileSetup||['supplyTile','autoSupplyTile'].includes(type),'타일에 인쇄된 자원을 공급 주머니에서 먼저 놓아주세요.');assert(!g.gathering||['gatherTake','autoGather','gatherDiscard','finishGather','bagMove','discardItem','eat'].includes(type),'진행 중인 채집을 먼저 마쳐주세요.');assert(!g.payment||['offerPayment','returnPayment','cancelPayment','commitPayment'].includes(type),'지불 칸의 재료를 확인하거나 지불을 취소해주세요.');assert(!g.pendingExplore||['resolveExplore','supplyTile','autoSupplyTile'].includes(type),'발견한 지형으로 이동할지, 현재 위치에 머물지 먼저 선택해주세요.');if(type==='autoSupplyTile'){validTurn(g,true);const setup=g.tileSetup;assert(setup&&setup.remaining.length&&g.tiles[setup.tile]&&(a.to===undefined||a.to===setup.tile),'자원을 배치할 발견 타일이 없습니다.');assert(g.pendingExplore?.player===p.id&&g.pendingExplore.to===setup.tile,'현재 탐험가가 발견한 타일의 자원만 놓을 수 있습니다.');for(const kind of setup.remaining.slice())actMutable(g,'supplyTile',{kind,to:setup.tile});return g;}if(type==='supplyTile'){validTurn(g,true);const setup=g.tileSetup;assert(setup&&a.to===setup.tile,'자원을 배치할 발견 타일을 선택해주세요.');const at=setup.remaining.indexOf(a.kind);assert(at>=0&&RES[a.kind],'이 타일에는 해당 자원을 더 놓을 수 없습니다.');g.tiles[setup.tile].resources.push(a.kind);setup.remaining.splice(at,1);if(!setup.remaining.length)g.tileSetup=null;return g;}
    if(type==='stackFood'){stackFood(g,a);return g;}if(type==='splitFood'){splitFood(g,a);return g;}
    if(type==='escape')throw new Error('개인 탈출은 공용 비행기 출발로 대체되었습니다.');if(type==='installAircraft'){installAircraft(g,a);return g;}if(type==='departAircraft'){departAircraft(g);return g;}
    if(type==='beginPayment'){beginPayment(g,a.type,a.data||{});return g;}if(PAID_TYPES.includes(type)){beginPayment(g,type,a);return g;}
    if(type==='offerPayment'){validTurn(g,true);offerPayment(g,a.id);return g;}if(type==='returnPayment'){validTurn(g,true);const {tray}=paymentItems(g),at=tray.offered.indexOf(a.id);assert(at>=0,'지불 칸에 없는 물건입니다.');tray.offered.splice(at,1);return g;}if(type==='cancelPayment'){validTurn(g,true);paymentItems(g);g.payment=null;return g;}if(type==='commitPayment'){validTurn(g,true);commitPayment(g);return g;}
    if(type==='autoGather'){validTurn(g,true);autoGather(g);return g;}
    if(type==='startGather'||type==='gather'){startGather(g,a.card);return g;}if(type==='gatherTake'||type==='gatherDiscard'){validTurn(g,true);gatherTake(g,a,type==='gatherDiscard');return g;}if(type==='finishGather'){validTurn(g,true);const s=g.gathering;assert(s&&s.player===p.id&&s.tile===p.pos,'진행 중인 채집이 없습니다.');assert(canFinishGather(g),'집중채집은 담을 수 있는 남은 자원을 모두 가져와야 합니다. 공간이 없으면 지형에 남길 수 있습니다.');g.gathering=null;return g;}
    if(type==='resolveExplore'){validTurn(g);const choice=g.pendingExplore;assert(choice&&choice.player===p.id&&choice.from===p.pos&&neighbors(choice.from).includes(choice.to)&&g.tiles[choice.to],'이동을 선택할 탐험 결과가 없습니다.');assert(typeof a.move==='boolean','이동 또는 머무르기를 선택해주세요.');assert(a.to===undefined||a.to===choice.to,'방금 발견한 지형으로만 이동할 수 있습니다.');if(a.move)assert(capacityOK(g,choice.to,p),'그 타일에는 이미 탐험가 2명이 있습니다.');g.pendingExplore=null;if(a.move)enterTile(g,p,choice.to,false,'탐험 후 이동');else log(g,`${p.name} · 지형만 공개하고 현재 위치에 머뭅니다.`);return g;}if(type==='hunt'){validTurn(g);assert(g.actions>0,'남은 행동이 없습니다.');assert(g.tiles[p.pos]?.hunt,'현재 지형에 사냥감이 없습니다.');encounter(g,g.tiles[p.pos],true);return g;}if(type==='battleContinue'){assert(g.battle?.stage==='choice'&&g.battle.player===p.id&&g.actions>0&&!g.ended&&g.winner===null,'다시 전투할 행동이 없습니다.');g.battle.stage='plan';g.battle.optional=true;return g;}if(type==='battleStop'){assert(g.battle?.player===p.id&&(g.battle.stage==='choice'||g.battle.stage==='plan'&&g.battle.optional)&&!g.ended&&g.winner===null,'한 라운드를 마친 뒤 전투를 멈출 수 있습니다.');pauseBattle(g);return g;}if(type==='battleAssist'){const b=g.battle,other=g.players[a.player];assert(b?.stage==='plan'&&b.player===p.id&&g.actions>0&&!g.ended&&g.winner===null&&!b.assist&&other&&other.id!==p.id&&other.pos===p.pos&&(b.partner===null||b.partner===other.id),'같은 칸의 동료 한 명이 계획 단계에서 지원할 수 있습니다.');assert(other.combatHand[a.card],'지원할 공격 카드를 선택해주세요.');b.partner=other.id;b.assist={player:other.id,card:other.combatHand.splice(a.card,1)[0]};log(g,other.name+'이 공동 사냥에 참여합니다.');return g;}if(type==='battleStep'){battleStep(g);return g;}if(type==='battlePlan'){assert(g.battle?.stage==='plan'&&g.battle.player===p.id&&!g.ended&&g.winner===null,'카드를 계획할 수 없는 단계입니다.');assert(g.actions>0,'전투 한 라운드에는 행동 1회가 필요합니다.');assert(Array.isArray(a.cards)&&a.cards.length===3&&new Set(a.cards).size===3&&a.cards.every(i=>Number.isInteger(i)&&p.combatHand[i]),'서로 다른 카드 3장을 순서대로 선택해주세요.');g.actions--;g.battle.roundPaid=true;g.battle.optional=false;g.battle.plan=a.cards.map(i=>p.combatHand[i]);a.cards.slice().sort((x,y)=>y-x).forEach(i=>p.combatHand.splice(i,1));g.battle.order=takeActionCard(g).order;g.battle.stage='resolve';g.battle.feed.unshift(`행동 카드 ${g.battle.order.split('').join(' → ')} · ? 행동에 앞에서부터 순서대로 적용`);return g;}
    if(type==='place'){validTurn(g,true);place(g,a);return g;}if(type==='discardPiece'){validTurn(g,true);let returned;if(a.source==='pending'){assert(g.pending.length,'버릴 조각이 없습니다.');returned=g.pending.shift();}else{const s=p.storage.find(s=>s.cells.some(c=>c?.id===a.source));assert(s,'보관된 조각이 없습니다.');returned=s.cells.find(c=>c?.id===a.source);s.cells=s.cells.map(c=>c?.id===a.source?null:c);}returnPiece(g,returned);log(g,'놓을 공간이 없는 자재 조각을 공용 공급에 반납했습니다.');return g;}
    if(type==='autoCollectLoot'){validTurn(g,true);const owner=g.players.find(p=>p.id===context.lootOwner);assert(owner,'자동으로 받을 물건이 없습니다.');for(const item of g.loot.filter(i=>i.owner===owner.id)){const fit=findBagSpace(owner,item,true);if(!fit)continue;delete fit.owner;if(fit.source==='crafted')delete fit.source;owner.bag.push(fit);g.loot.splice(g.loot.findIndex(i=>i.id===item.id),1);}return g;}
    if(type==='placeLoot'){validTurn(g,true);const owner=lootOwner(g),at=a.id===undefined?0:g.loot.findIndex(i=>i.id===a.id),item=g.loot[at];assert(item&&item.owner===owner.id,'이번 탐험가에게 지급할 물건을 선택해주세요.');const placed={...item,rotation:a.rotation??item.rotation??0,flip:a.flip??item.flip??false,x:a.x,y:a.y};delete placed.owner;if(placed.source==='crafted')delete placed.source;assert(bagFits(owner,placed,a.x,a.y),'빈 가방 칸에 모양을 맞춰 놓아주세요. 잠긴 칸에는 놓을 수 없습니다.');owner.bag.push(placed);g.loot.splice(at,1);return g;}
    if(type==='discardItem'){validTurn(g,true);const owner=lootOwner(g),i=owner.bag.findIndex(i=>i.id===a.id);assert(i>=0,'가방에 없는 물건입니다.');const item=owner.bag.splice(i,1)[0];leaveOnGround(g,item,owner.pos);log(g,`${itemName(item)}을 현재 지형에 내려놓았습니다. 다시 가져오려면 채집 카드를 사용하세요.`);return g;}if(type==='discardLoot'){validTurn(g,true);const owner=lootOwner(g),at=a.id===undefined?0:g.loot.findIndex(i=>i.id===a.id);assert(at>=0&&g.loot[at]?.owner===owner.id,'이번 탐험가의 대기 물건을 선택해주세요.');leaveOnGround(g,g.loot.splice(at,1)[0]);return g;}
    if(type==='bagMove'){validTurn(g,true);const owner=lootOwner(g),i=owner.bag.find(i=>i.id===a.id);assert(i,'가방에 없는 물건입니다.');const moved={...i,rotation:a.rotation??i.rotation??0,flip:a.flip??i.flip??false};assert(bagFits(owner,moved,a.x,a.y),'그 칸에는 물건을 놓을 수 없습니다.');Object.assign(i,moved,{x:a.x,y:a.y});return g;}
    if(type==='eat'){validTurn(g,true);const i=p.bag.findIndex(i=>i.id===a.id);assert(i>=0&&foodValue(p.bag[i])>0,'먹을 수 있는 음식이 아닙니다.');assert(p.hunger<6,'포만감이 이미 가득합니다.');const item=p.bag.splice(i,1)[0],value=foodValue(item);p.hunger=Math.min(6,p.hunger+value);for(const area of ['hand','discard','deck']){const h=p[area].indexOf('hunger');if(h>=0){p[area].splice(h,1);break;}}log(g,`${itemName(item)} 섭취 · 포만감 +${value}`,'good');return g;}
    validTurn(g);
    if(type==='trade'){const other=g.players[a.player],i=p.bag.find(v=>v.id===a.id);assert(other&&other.id!==p.id&&other.pos===p.pos&&i,'같은 칸의 다른 탐험가에게만 물건을 건넬 수 있습니다.');p.bag=p.bag.filter(v=>v.id!==i.id);g.loot.push({...i,owner:other.id,origin:p.pos});log(g,`${p.name} → ${other.name} · ${itemName(i)} 전달 · 받는 가방에 배치하세요.`);return g;}
    if(type==='end'){endTurn(g);return g;}
    if(type==='explore'){card(g,a.card,'explore');assert(exploreTargets(g).includes(a.to),'자신의 위치 옆 빈 칸을 선택해주세요.');assert(g.terrainDeck.length,'지형 덱을 모두 사용했습니다.');assert(a.level===1||a.level===2,'지형 레벨을 선택해주세요.');assert(a.level===1||dist(a.to,'0,0')>=2,'2레벨 지형은 캠프에서 2칸 이상 떨어진 곳에 놓습니다.');spend(g,[a.card]);let t=g.terrainDeck.pop();g.discoveries++;const level=t.terrain==='escape'?1:a.level;let resources=t.resources.slice();if(level===2){const idx=resources.findIndex(k=>['stone','stem','branch'].includes(k));if(idx>=0)resources[idx]='metal';}g.tiles[a.to]={...t,resourcePlan:resources.slice(),resources:[],groundItems:[],level,safe:t.terrain==='escape',hunt:t.terrain!=='escape'&&(level===2||!t.event&&g.discoveries%3===0)?{}:null,eventDone:false};g.tileSetup=resources.length?{tile:a.to,remaining:resources.slice()}:null;g.pendingExplore={player:p.id,from:p.pos,to:a.to};log(g,`${TERRAIN[t.terrain].name} Lv.${level} 발견${g.tiles[a.to].hunt?' · 사냥감 흔적':''} · 이동 여부를 선택하세요.`,'good');}
    else if(type==='move'){const running=a.run===true;if(running)card(g,a.card,'run');const path=routes(g,p.pos,running?2:1)[a.to];assert(path?.length,'도달할 수 있는 공개 타일을 선택해주세요.');assert(capacityOK(g,a.to),'그 타일에는 이미 탐험가 2명이 있습니다.');spend(g,[a.card]);enterTile(g,p,a.to,running);}
    else if(type==='hide'){const tile=g.tiles[p.pos],kind=traceResource(tile);spend(g,[a.card]);detect(g,-1);if(kind)tile.resources.push(kind);log(g,`흔적 지우기 · 발각 −1${kind?' · '+RES[kind].name+' 1개를 현재 지형에 생성':' · 인쇄 자원이 없는 지형'}`);}
    else if(type==='rest'){assert(g.tiles[p.pos].safe,'안전한 캠프에서만 휴식할 수 있습니다.');assert(p.hp<8,'체력이 이미 가득합니다.');spend(g,[a.card]);p.hp=Math.min(8,p.hp+2);log(g,'휴식 · 체력 +2','good');}
    else if(type==='survey'){assert(g.tiles[p.pos].level===2&&!p.surveyed,'아직 조사하지 않은 2레벨 지형에서 사용할 수 있습니다.');assert(!g.tiles[p.pos].hunt,'사냥감을 먼저 해결해야 합니다.');spend(g,[a.card]);p.surveyed=true;gain(g,p,['battery']);detect(g,2);log(g,'유적 조사 · 항공 배터리 획득 / 발각 +2','good');}
    else throw new Error('지원하지 않는 행동입니다.');return g;
  }
  function act(g,type,a={}){const next=clone(g),context=type==='autoCollectLoot'?{lootOwner:next.loot[0]?.owner}:{};settleLootOverflow(next);actMutable(next,type,a,context);settleLootOverflow(next);finishDeparture(next);settleLootOverflow(next);settleCombatTurn(next);for(const k of Object.keys(g))delete g[k];Object.assign(g,next);return g;}
  function migrateSave(raw){assert(raw&&(raw.version===1||raw.version===2)&&Array.isArray(raw.players)&&raw.players.length,'지원하지 않는 저장 파일입니다.');const recoverExplore=!Object.prototype.hasOwnProperty.call(raw,'pendingExplore');const g=clone(raw);if((g.basicDeckRevision||1)<2){for(const [i,p]of g.players.entries()){if(['hand','deck','discard'].flatMap(k=>p[k]||[]).filter(c=>c==='hide').length<2)p.deck.unshift('hide');const initial=g.setupDecks?.[i];if(Array.isArray(initial)&&initial.filter(c=>c==='hide').length<2)initial.unshift('hide');}g.basicDeckRevision=2;}g.battleEffect=g.battleEffect||null;g.huntResult=g.huntResult||null;g.combatTurnEnd=g.combatTurnEnd||null;for(const p of g.players)p.pendingHunt=p.pendingHunt||null;if(g.battle&&PREY[g.battle.kind]){g.battle.player??=active(g).id;g.battle.roundPaid??=g.battle.stage==='resolve';g.battle.optional??=false;g.battle.pattern=battlePattern(g.battle).slice();g.battle.prepared=Math.max(0,Number(g.battle.prepared)||0);}g.sharedDetection=sharedDetectionValue(g);g.pending=g.pending||[];restoreBuildings(g);restorePieceSupply(g);g.pendingEvent=g.pendingEvent||null;g.pendingDeparture=g.pendingDeparture||null;g.events=Array.isArray(g.events)?g.events:[];g.eventDiscard=Array.isArray(g.eventDiscard)?g.eventDiscard:Object.keys(EVENT_CARDS).filter(id=>!g.events.includes(id)&&g.pendingEvent?.card!==id);g.pendingExplore=g.pendingExplore||null;g.tileSetup=g.tileSetup||null;g.gathering=g.gathering||null;g.payment=g.payment||null;g.loot=g.loot||[];for(const t of Object.values(g.tiles||{})){if(!Array.isArray(t.resourcePlan))t.resourcePlan=printedResources(t);t.groundItems=Array.isArray(t.groundItems)?t.groundItems:[];}g.serial=Math.max(1,Number(g.serial)||1);const allIds=[...g.players.flatMap(p=>p.bag||[]),...g.loot,...allGroundItems(g),...allPieces(g),...Object.values(g.aircraft?.zones||{}).flatMap(z=>z.cells||[]).filter(Boolean)].flatMap(itemParts).map(i=>Number(String(i?.id||'').replace(/^i/,''))).filter(Number.isFinite);if(allIds.length)g.serial=Math.max(g.serial,Math.max(...allIds)+1);g.loot=g.loot.map(i=>typeof i==='string'?makeItem(g,i,{owner:g.players[g.turn].id,origin:g.players[g.turn].pos}):{rotation:0,flip:false,owner:g.players[g.turn].id,...i});for(const item of g.loot)item.origin=lootOrigin(g,item);for(const [tile,t]of Object.entries(g.tiles||{}))t.groundItems=t.groundItems.map(item=>{const normalized=typeof item==='string'?makeItem(g,item,{origin:tile}):{rotation:0,flip:false,...item,origin:tile};delete normalized.owner;return normalized;});
    const obsoleteStart=i=>i.source==='starting-supply'&&i.kind==='berry'&&!Object.prototype.hasOwnProperty.call(i,'x')&&!Object.prototype.hasOwnProperty.call(i,'y')&&!i.topping&&i.origin==='0,0';const unclaimedStarting=g.loot.filter(obsoleteStart).length;if(unclaimedStarting){g.loot=g.loot.filter(i=>!obsoleteStart(i));log(g,'아직 받지 않은 시작 선지급 산딸기를 정리했습니다. 이제 각 탐험가가 캠프를 떠날 때 산딸기 1개를 받습니다.');}
    for(const p of g.players){p.bagUnlocks=bagUnlocked(p).slice();p.capacity=12+3*p.bagUnlocks.length;const old=(p.bag||[]).map(value=>{const item={rotation:0,flip:false,...value};if(!item.id)item.id=uid(g);if(g.version===1){item.x++;item.y++;}return item;});p.bag=[];for(const item of old.slice().sort((a,b)=>Number(a.kind==='ration')-Number(b.kind==='ration'))){const fit=bagFits(p,item,item.x,item.y)?item:findBagSpace(p,item,true);if(fit)p.bag.push(fit);else g.loot.push({...item,owner:p.id,origin:g.tiles[item.origin]?item.origin:p.pos});}const placed=new Map(p.bag.map(i=>[i.id,i]));p.bag=old.map(i=>placed.get(i.id)).filter(Boolean);}
    if(recoverExplore&&!g.pendingDeparture&&!g.pendingEvent&&!g.tileSetup&&!g.gathering&&!g.payment&&!g.ended&&g.winner===null&&!g.battle&&!g.loot.length&&!g.pending?.length&&[0,1].includes(g.actions)&&g.discoveries>0){const p=active(g),last=Object.entries(g.tiles||{}).at(-1);if(p&&last){const [to,t]=last,expected=TERRAIN[t.terrain]?`${TERRAIN[t.terrain].name} Lv.${t.level} 발견${t.hunt?' · 사냥감 흔적':''}`:null;if(expected&&g.log?.[0]?.text===expected&&p.pos!==to&&neighbors(p.pos).includes(to)&&!t.eventDone)g.pendingExplore={player:p.id,from:p.pos,to};}}
    validateSavedFood(g);restoreAircraft(g);g.winners=Array.isArray(g.winners)?g.winners:g.winner!==null?[g.winner]:[];if(g.payment?.type==='escape'){g.payment=null;log(g,'기존 개인 탈출 준비를 취소했습니다. 재료와 카드는 보존되며 공용 비행기를 이용합니다.');}
    if(g.payment?.type==='cook'&&(g.payment.data?.tea===true||g.payment.data?.items?.length>1&&(!Array.isArray(g.payment.data.cards)||g.payment.data.cards.length!==g.payment.data.items.length))){g.payment=null;log(g,'이전 조리 준비를 취소했습니다. 음식마다 카드 한 장을 선택해주세요. 재료·카드·행동은 보존됩니다.');}
    if(g.payment?.type==='process'){const costs={};let valid=true;for(const r of g.payment.data?.recipes||[]){const recipe=pieceRecipe(r.material,r.shape);if(!recipe?.craftable){valid=false;break;}const rawKind=MATERIALS[r.material].raw;costs[rawKind]=(costs[rawKind]||0)+recipe.cost;}const same=valid&&Object.keys(costs).length===Object.keys(g.payment.cost||{}).length&&Object.entries(costs).every(([k,n])=>g.payment.cost[k]===n);if(!raw.pieceSupply||!same){g.payment=null;log(g,'가공 비용과 공용 재고 규칙이 바뀌어 이전 지불 준비를 취소했습니다. 재료·카드·행동은 보존됩니다.');}}
    settleLootOverflow(g);finishDeparture(g);settleLootOverflow(g);if(g.battle?.stage==='plan'&&g.actions===0){const p=active(g),origin=g.battle.origin;pauseBattle(g);p.pendingHunt=origin;}settleCombatTurn(g);checkDetection(g);g.version=2;return g;
  }
  const api={aircraftCells,aircraftPoints,AIRCRAFT_STEEL_SHAPES,traceResource,printedResources,battlePattern,preyAction,battleAction,DETECTION_MAX,SHARED_DETECTION_MAX,canFitItem,groundItems,tileResourceCount,canFinishGather,PIECE_RECIPES,pieceCost,pieceStock,boardMask,boardLevels,EVENT_CARDS,FOOD_STACKS,foodValue,itemName,canStackFood,materialCount,AIRCRAFT_ZONES,AIRCRAFT_RECIPES,AIRCRAFT_POINTS,aircraftProgress,canInstallAircraft,BAG,BASIC_DECK,RES,TERRAIN,CARDS,COMBAT,SHAPES,MATERIALS,BUILDINGS,PREY,DINOS,DIR,key,pos,dist,neighbors,clone,active,newGame,act,routes,capacityOK,exploreTargets,shape,pieceCells,board,canPlace,itemCells,bagFits,bagCells,bagUnlocked,lootOwner,migrateSave,paymentPlan,count,hasCost,cardData,dinosaurTurn,spawnDino,encounter,addItem};root.DinoEngine=api;if(typeof module!=='undefined')module.exports=api;
})(typeof globalThis!=='undefined'?globalThis:this);
